// Generated by build-app.sh from bridge/capture/mac/BUNDLE_ID (your build) and
// app/desktop/build/bridge/capture/mac/BUNDLE_ID (NeverQuestAlone's, --public), the
// one place each build's bundle id is set (PRD PF-6): Info.plist, the code requirement
// in bridge/transport/capture.mjs and this check all read it. Edit those, not this.
#if NQA_PUBLIC_ID
let captureBundleId = "com.neverquestalone.capture"
#else
let captureBundleId = "com.neverquestalone.capture.dev"
#endif
