#!/usr/bin/env node
// tools/qol-quests/generate.mjs: writes QoL.lua's STARTS and HANDIN lists
// (between the "generated" markers) from the emulator's facts (cmangos.json,
// by extract.mjs) and the review of them (reviewed.json). Nobody edits the
// lists by hand; tests/qol_test.mjs fails when QoL.lua and this disagree.
//
//   node tools/qol-quests/generate.mjs           rewrite the block in QoL.lua
//   node tools/qol-quests/generate.mjs --check   exit 1 if it's out of date
//
// The rules (README.md says why):
//   Accepting starts
//     an escort   an accept hook that starts an escort or a follower
//     a fight     an accept hook that attacks or summons; a start script that
//                 summons a creature hostile to whoever can take the quest,
//                 attacks, or turns a creature hostile
//     a flight    a start script's taxi
//     a move      a start script's teleport, or a spell (the start script's, or
//                 the quest's own on accepting) that teleports you
//     an event    a start script's spawn group; any other accept hook
//     timed       a time limit (quest_template.LimitTime)
//   One quest, several: the first in that order. reviewed.json's "accept" sets
//   a kind the rules can't see (a spell, a walk) or corrects one, with why.
//   Handing in starts
//     a fight     an end script as above; a rewarded hook that attacks or summons
//     a flight    an end script's taxi
//     a move      an end script's teleport, or a spell (the end script's,
//                 or the quest's own on the reward) that teleports you
//   reviewed.json's "handin" judges the rest (other rewarded hooks, spells).
//   "none" in reviewed.json leaves a quest out, with why. "extra" adds a quest
//   the emulator doesn't script, with its source.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const LUA = path.join(HERE, "..", "..", "addon", "NeverQuestAlone", "QoL.lua");
export const BEGIN = "-- BEGIN generated by tools/qol-quests/generate.mjs: don't edit by hand";
export const END = "-- END generated";

const ACCEPT_ORDER = ["escort", "fight", "flight", "moves", "event", "timed"];
const HANDIN_KINDS = ["fight", "flight", "moves"];
const ESCORT = /^(Start|StartEscort|DoStartEscort|StartRiggerEscort|StartFollow|AI_EVENT_START_ESCORT)$/;
const FIGHT = /^(AttackStart|SummonCreature)$/;

function hostileEffect(e) {
	return (e.do === "summon" && e.hostile) || e.do === "attack" || (e.do === "faction" && e.hostile);
}

// The kinds the facts show, in no order.
function acceptKinds(q) {
	const kinds = new Set();
	for (const e of q.accept) {
		if (e.via === "accept hook") {
			if (e.signals.some((s) => FIGHT.test(s))) kinds.add("fight");
			else if (e.signals.some((s) => ESCORT.test(s))) kinds.add("escort");
			else kinds.add("event");
		} else if (hostileEffect(e)) kinds.add("fight");
		else if (e.do === "taxi") kinds.add("flight");
		else if (e.do === "teleport" || e.teleports) kinds.add("moves");
		else if (e.do === "spawngroup") kinds.add("event");
	}
	if (q.limit > 0) kinds.add("timed");
	return kinds;
}
function handinKinds(q) {
	const kinds = new Set();
	for (const e of q.handin) {
		if (e.via === "rewarded hook") {
			if (e.signals.some((s) => FIGHT.test(s))) kinds.add("fight");
		} else if (hostileEffect(e)) kinds.add("fight");
		else if (e.do === "taxi") kinds.add("flight");
		else if (e.do === "teleport" || e.teleports) kinds.add("moves");
	}
	return kinds;
}
const first = (kinds, order) => order.find((k) => kinds.has(k));

// The two lists: id -> { kind, title }. Throws on a review that no longer
// matches the facts, so a stale one can't hide.
export function lists(facts, review) {
	const out = { accept: new Map(), handin: new Map() };
	const problems = [];
	for (const [side, derive, order] of [["accept", acceptKinds, ACCEPT_ORDER], ["handin", handinKinds, HANDIN_KINDS]]) {
		for (const [id, q] of Object.entries(facts.quests)) {
			const kind = first(derive(q), order);
			if (kind) out[side].set(Number(id), { kind, title: q.title });
		}
		for (const [id, r] of Object.entries(review[side] || {})) {
			if (!r.why) problems.push(`${side} ${id}: a review needs its why`);
			const q = facts.quests[id];
			if (!q) {
				problems.push(`${side} ${id}: reviewed but not in cmangos.json (use "extra")`);
				continue;
			}
			const derived = out[side].get(Number(id))?.kind;
			if (r.kind === derived) problems.push(`${side} ${id}: the review says what the rules already say`);
			if (r.kind === "none") out[side].delete(Number(id));
			else if ((side === "accept" ? ACCEPT_ORDER : HANDIN_KINDS).includes(r.kind)) out[side].set(Number(id), { kind: r.kind, title: q.title });
			else problems.push(`${side} ${id}: unknown kind ${r.kind}`);
		}
	}
	for (const [id, r] of Object.entries(review.extra || {})) {
		if (facts.quests[id]) problems.push(`extra ${id}: the emulator scripts it now; review it under "${r.side}"`);
		if (!r.why || !r.title) problems.push(`extra ${id}: needs a title and a why`);
		out[r.side].set(Number(id), { kind: r.kind, title: r.title });
	}
	if (problems.length) throw new Error("generate.mjs:\n  " + problems.join("\n  "));
	return out;
}

// A title is third-party text written into a Lua comment: a line break or any
// other control character would end the comment and run the rest as code.
function printable(id, title) {
	if (typeof title !== "string" || /[\u0000-\u001f\u007f]/.test(title)) {
		throw new Error(`generate.mjs: quest ${id}'s title has a control character; refusing to write it into QoL.lua`);
	}
	return title;
}

function luaTable(name, list) {
	const lines = [...list.entries()].sort((a, b) => a[0] - b[0]).map(([id, { kind, title }]) => `\t[${id}] = "${kind}", -- ${printable(id, title)}`);
	return [`local ${name} = {`, ...lines, "}", `Q.${name} = ${name}`];
}

// The block, markers included.
export function render(facts, review) {
	const l = lists(facts, review);
	const s = facts.sources;
	const NAMES = { escort: ["escort", "escorts"], fight: ["fight", "fights"], flight: ["flight", "flights"], moves: ["teleport", "teleports"], event: ["event", "events"], timed: ["timed", "timed"] };
	const counts = (side, kinds) => kinds.map((k) => {
		const n = [...l[side].values()].filter((v) => v.kind === k).length;
		return `${n} ${NAMES[k][n === 1 ? 0 : 1]}`;
	}).join(", ");
	return [
		BEGIN,
		"-- From the emulator's quest scripts and hooks by generate.mjs's rules, with",
		"-- reviewed.json's corrections (each checked on Wowhead Classic). Sources:",
		`--   ${s.db}`,
		`--   ${s.scripts} (ScriptDevAI quest hooks)`,
		`--   ${s.factions} (who's hostile to whom)`,
		`--   ${s.spells} (which spells move you)`,
		"-- tools/qol-quests/README.md says how to refresh them.",
		"-- Quests whose acceptance starts something: Auto Accept Quests leaves them",
		`-- to you. ${counts("accept", ACCEPT_ORDER)}.`,
		"-- An escort's tag (84), \"escort\" in its objectives or a time limit the",
		"-- game reports counts too, for any this list misses.",
		...luaTable("STARTS", l.accept),
		"-- Quests whose hand-in starts a fight, a flight or a teleport: Auto Turn In Quests",
		`-- leaves them to you. ${counts("handin", HANDIN_KINDS)}.`,
		...luaTable("HANDIN", l.handin),
		END,
	].join("\n");
}

export function load() {
	const read = (f) => JSON.parse(fs.readFileSync(path.join(HERE, f), "utf8"));
	return { facts: read("cmangos.json"), review: read("reviewed.json") };
}

// QoL.lua with its block replaced by `block`.
export function splice(lua, block) {
	const a = lua.indexOf(BEGIN);
	const b = lua.indexOf(END, a);
	if (a < 0 || b < 0) throw new Error(`generate.mjs: no generated block in ${LUA}`);
	return lua.slice(0, a) + block + lua.slice(b + END.length);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
	const { facts, review } = load();
	const lua = fs.readFileSync(LUA, "utf8");
	const next = splice(lua, render(facts, review));
	if (process.argv.includes("--check")) {
		if (next !== lua) {
			console.error("generate.mjs: QoL.lua's STARTS/HANDIN are out of date; run node tools/qol-quests/generate.mjs");
			process.exit(1);
		}
		console.log("generate.mjs: QoL.lua is up to date");
	} else {
		fs.writeFileSync(LUA, next);
		const l = lists(facts, review);
		console.log(`generate.mjs: STARTS ${l.accept.size}, HANDIN ${l.handin.size} -> ${LUA}`);
	}
}
