#!/usr/bin/env node
// tools/quest-chains/generate.mjs: writes the quest chains the addon knows
// (Chains.lua, between the "generated" markers) from the emulator's facts
// (cmangos.json, by extract.mjs) and the review of them (reviewed.json). Nobody
// edits the block by hand; tests/quest_chains_test.mjs fails when Chains.lua and
// this disagree.
//
//   node tools/quest-chains/generate.mjs           rewrite the block in Chains.lua
//   node tools/quest-chains/generate.mjs --check   exit 1 if it's out of date
//   node tools/quest-chains/generate.mjs --show 65 the quest's record per race and class
//
// The rules (README.md says why):
//   A quest a player can do: enabled, started by a creature, an object or an
//     item, not repeatable, not a world event's, open to their race and class
//     (the template's masks), and offered to their race by a quest giver (one
//     that wouldn't attack them, or an object or item). Each race and class
//     the game pairs (40, by CharBaseInfo) is worked out on its own, so a step
//     count is never another faction's or class's, and a record shared by all
//     is one every one of them has.
//   A step: the quests it needs are the template's PrevQuestId and every quest
//     whose NextQuestId is it. Any one of them opens it, but a quest in an
//     each-from-all group (ExclusiveGroup below 0) counts only with the whole
//     group done. A quest that needs nothing is step 1; else its step is one
//     past the quest it needs, or past the group's last (a group done side by
//     side is one step). Two ways in at different steps leave the step
//     unknown, and everything after it.
//   A breadcrumb, or the quest a quest giver only offers next (NextQuestInChain
//     with no need of it), is no step: a player can start the chain without it.
//     A breadcrumb (BreadcrumbForQuestId) still leads where the quest it points
//     at leads, with no step.
//   A payoff: a dungeon or raid quest, or a rare or better reward.
//     A dungeon or raid quest: tagged Dungeon or Raid (Type 81 or 62) and filed
//       under a party or raid instance (an area inside its map, its map's own
//       area, or an area with the same name, like Uldaman in the Badlands); or
//       every objective found only on one such instance's map.
//     A reward: an item of quality 3 (rare) or better, fixed or a choice, that
//       the class can equip (the item's class mask, and the weapon or armor
//       proficiency its subclass needs, from wago.tools' skills). A choice
//       says how many other rare or better picks the class could take instead;
//       a reward the class can't equip, fixed or picked, is no payoff for it.
//   What a quest leads to: the nearest dungeon or raid among it and the quests
//     after it, else the best reward among them (the highest quality, then the
//     nearest). A chain's first quest never leads to itself.
//   Of M: the step of that payoff's quest, counted along this quest's way to it;
//     for a dungeon or raid, of the last quest in that instance after it (a chain
//     with three Uldaman quests in a row is "of" the third). Ways of different
//     lengths, or a group whose other quests' steps aren't known, leave it
//     unknown.
//   A quest with a payoff gets a record; one whose record differs by class (or
//     by race) gets one per class (or race); one that differs by both, or that
//     names two payoffs for one class, says less (see degrade()).
//   reviewed.json corrects what the rules can't see, each with its why.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const LUA = path.join(HERE, "..", "..", "addon", "NeverQuestAlone", "Chains.lua");
export const BEGIN = "-- BEGIN generated by tools/quest-chains/generate.mjs: don't edit by hand";
export const END = "-- END generated";

// The playable races and classes, as the templates' masks have them (race and class ids 1 up: bit id - 1).
export const RACES = [1, 2, 4, 8, 16, 32, 64, 128];
export const CLASSES = [1, 2, 4, 8, 16, 64, 128, 256, 1024];
/** The race and class pairs the game has (facts.combos, CharBaseInfo; every pair when the facts have none). */
export const pairs = (facts) => RACES.flatMap((r) => CLASSES.filter((c) => !facts.combos || ((facts.combos[r] || 0) & c) !== 0).map((c) => [r, c]));
export const QUALITY = { 3: "rare", 4: "epic", 5: "legendary" };
const DUNGEON = 81, RAID = 62;
const PARTY = 1, RAID_MAP = 2; // Map.InstanceType

export function load() {
	const read = (f) => JSON.parse(fs.readFileSync(path.join(HERE, f), "utf8"));
	return { facts: read("cmangos.json"), review: read("reviewed.json") };
}

const bare = (s) => String(s || "").replace(/^The /, "");

/**
 * The party and raid instances: map -> { map, area (the area that names it), name (English), raid }, and
 * the areas a quest can be filed under for each: area -> map. The area that names an instance is one inside
 * its map with its map's name (a leading "The " aside), else its map's own area, else reviewed.json's.
 */
export function instancesOf(facts, review) {
	const out = new Map();
	const named = new Map(); // area -> map
	const unnamed = new Set(); // maps no area names (a raid that never opened, the Emerald Dream): no quest's payoff
	const problems = [];
	for (const [id, inst] of Object.entries(facts.instances)) {
		if (inst.kind !== PARTY && inst.kind !== RAID_MAP) continue;
		const map = Number(id);
		const fix = review.instances?.[id];
		let area = Number(Object.entries(inst.inside).find(([, n]) => bare(n) === bare(inst.name))?.[0]) || inst.area || 0;
		if (fix) {
			if (!fix.why) problems.push(`instance ${id}: a review needs its why`);
			if (fix.area === area) problems.push(`instance ${id}: the review says what the rules already say`);
			area = fix.area;
		}
		if (!area) { unnamed.add(map); continue; }
		const name = inst.inside[area] || facts.zones[area]?.name || (area === inst.area ? inst.name : null);
		out.set(map, { map, area, name: name || inst.name, raid: inst.kind === RAID_MAP });
		named.set(area, map);
		for (const a of Object.keys(inst.inside)) named.set(Number(a), map);
	}
	// An area outside the map with the instance's own name: the quest log's header for it (Uldaman in the
	// Badlands, Zul'Farrak in Tanaris). Not any area inside the map: the Deadmines' map holds a Westfall too.
	for (const [z, zone] of Object.entries(facts.zones)) {
		if (named.has(Number(z))) continue;
		for (const [map, inst] of out) {
			if (bare(zone.name) === bare(inst.name) || bare(zone.name) === bare(facts.instances[map].name)) named.set(Number(z), map);
		}
	}
	return { instances: out, named, unnamed, problems };
}

/** The rules' payoffs, before the review: quest -> { map } for a dungeon or raid quest. */
function dungeonOf(q, inst) {
	if ((q.type === DUNGEON || q.type === RAID) && inst.named.has(q.zone)) return inst.named.get(q.zone);
	const w = q.where || [];
	if (w.length === 1 && !q.unknown && (inst.instances.has(w[0]) || inst.unnamed.has(w[0]))) return w[0];
	return null;
}

/** The races that can take a quest: those its template allows that its quest givers offer it to. */
export const whoCan = (q) => (q.races || 255) & (q.takers ?? 255);

/**
 * Every quest's chain record for one race and class: quest -> record, or null for a quest they can take
 * that leads to nothing for them (so a record other races or classes share is never theirs too).
 */
export function profile(facts, review, r, c, ctx) {
	const Q = facts.quests;
	const can = (id) => {
		const q = Q[id];
		if (!q || q.disabled || q.noStarter || q.repeatable || q.event) return false;
		if (review.quests?.[id]?.skip) return false;
		return (whoCan(q) & r) !== 0 && (!q.classes || (q.classes & c) !== 0);
	};
	const routes = new Map(); // quest -> [[quest, ...], ...] (each route opens it), [] for a first step, null when this player can't
	const routesOf = (id) => {
		if (routes.has(id)) return routes.get(id);
		let out = null;
		if (can(id)) {
			const needs = ctx.needs.get(id) || [];
			if (!needs.length) out = [];
			else {
				out = [];
				const groups = new Set();
				for (const a of needs) {
					if (!can(a)) continue;
					const ex = Q[a].ex || 0;
					if (ex < 0) {
						if (groups.has(ex)) continue;
						groups.add(ex);
						out.push(ctx.groups.get(ex).filter(can));
					} else out.push([a]);
				}
				if (!out.length) out = null;
			}
		}
		routes.set(id, out);
		return out;
	};
	// A quest's step: { step (null when unknown), ok } or null when this player can't reach it.
	const steps = new Map();
	const stepOf = (id, stack = new Set()) => {
		if (steps.has(id)) return steps.get(id);
		if (stack.has(id)) return null; // a loop in the data: no step
		stack.add(id);
		const rs = routesOf(id);
		let res = null;
		if (rs) {
			if (!rs.length) res = { step: 1 };
			else {
				const found = new Set();
				let any = false, unknown = false;
				for (const route of rs) {
					const s = route.map((a) => stepOf(a, stack));
					if (s.some((x) => !x)) continue;
					any = true;
					if (s.some((x) => x.step === null)) { unknown = true; continue; }
					found.add(Math.max(...s.map((x) => x.step)) + 1);
				}
				if (any) res = { step: !unknown && found.size === 1 ? [...found][0] : null };
			}
		}
		stack.delete(id);
		steps.set(id, res);
		return res;
	};
	const children = new Map(); // quest -> [{ to, route }]
	for (const id of ctx.ids) {
		const rs = routesOf(id);
		if (!rs || !stepOf(id)) continue;
		for (const route of rs) for (const a of route) {
			if (!children.has(a)) children.set(a, []);
			children.get(a).push({ to: id, route });
		}
	}
	// A quest's reward for this class: the best rare or better item it can equip (the item's class mask,
	// and the weapon or armor proficiency its subclass needs), fixed before a choice; for a choice, how
	// many other rare or better picks it could take instead ("more"). null when it can equip none.
	const prof = facts.proficiencies || {};
	const canEquip = (it) => (!it.classes || (it.classes & c) !== 0) && (prof[it.class]?.[it.subclass] === undefined || (prof[it.class][it.subclass] & c) !== 0);
	const reward = (id) => {
		const all = [];
		for (const [item, choice] of Q[id].rewards || []) {
			const it = facts.items[item];
			if (it && it.quality >= 3) all.push({ item, quality: it.quality, choice: !!choice, fits: canEquip(it) });
		}
		const fits = all.filter((r) => r.fits);
		const fit = fits.sort((a, b) => b.quality - a.quality || a.choice - b.choice)[0];
		if (!fit) return null;
		return { rank: fit.quality, kind: "item", item: fit.item, quality: fit.quality, more: fit.choice ? fits.filter((r) => r.choice).length - 1 : 0 };
	};
	const result = new Map();
	for (const x of ctx.ids) {
		const sx = stepOf(x);
		if (!sx) continue;
		// The quests after x, nearest first (hops from x).
		const hops = new Map([[x, 0]]);
		const order = [x];
		for (let i = 0; i < order.length; i++) {
			for (const { to } of children.get(order[i]) || []) if (!hops.has(to)) { hops.set(to, hops.get(order[i]) + 1); order.push(to); }
		}
		// The steps along x's way (null: unknown), each quest after every quest it's reached from.
		const via = new Map(order.map((y) => [y, []])); // quest -> [{ from, route }] among those after x
		for (const a of order) for (const e of children.get(a) || []) if (e.to !== x) via.get(e.to).push({ from: a, route: e.route });
		const stage = new Map([[x, new Set([sx.step])]]);
		const left = new Map(order.map((y) => [y, via.get(y).length]));
		const ready = [x];
		while (ready.length) {
			const a = ready.shift();
			for (const { to, route } of children.get(a) || []) {
				if (to === x || !left.has(to)) continue;
				let s = null;
				const from = stage.get(a);
				if (!from.has(null) && from.size === 1) {
					const others = route.filter((m) => m !== a).map((m) => stepOf(m));
					if (!others.some((o) => !o || o.step === null)) s = Math.max([...from][0], ...others.map((o) => o.step)) + 1;
				}
				if (!stage.has(to)) stage.set(to, new Set());
				stage.get(to).add(s);
				left.set(to, left.get(to) - 1);
				if (left.get(to) === 0) ready.push(to);
			}
		}
		for (const y of order) if (!stage.has(y) || left.get(y) > 0) stage.set(y, new Set([null])); // a loop: unknown
		// The payoff: the nearest dungeon or raid, else the best reward; never x itself for a first step.
		const self = (y) => y === x && sx.step === 1;
		let pay = null;
		const dungeons = order.filter((y) => !self(y) && ctx.payoff.get(y) != null);
		if (dungeons.length) {
			const near = hops.get(dungeons[0]);
			const maps = new Set(dungeons.filter((y) => hops.get(y) === near).map((y) => ctx.payoff.get(y)));
			if (maps.size === 1) pay = { y: dungeons[0], kind: "dungeon", map: [...maps][0] };
		}
		if (!pay) {
			let best = null;
			for (const y of order) {
				if (self(y)) continue;
				const r = reward(y);
				if (r && (!best || r.rank > best.r.rank)) best = { y, r };
			}
			if (best) {
				const { rank: _rank, ...r } = best.r;
				pay = { y: best.y, ...r };
			}
		}
		if (!pay) { result.set(x, null); continue; }
		// Of: the step of the payoff's quest along x's way; for a dungeon or raid, of the last of the quests
		// after x in that instance. Then the one quest after x on every way to the farthest of them.
		const last = pay.kind === "dungeon" ? order.filter((y) => !self(y) && ctx.payoff.get(y) === pay.map) : [pay.y];
		const known = last.map((y) => stage.get(y)).every((st) => st.size === 1 && !st.has(null));
		const of = sx.step !== null && known ? Math.max(...last.map((y) => [...stage.get(y)][0])) : null;
		const end = last.reduce((a, y) => (hops.get(y) > hops.get(a) ? y : a), pay.y);
		let next = null;
		if (end !== x) {
			const onWay = new Set([end]);
			const back = [end];
			while (back.length) {
				const y = back.pop();
				for (const { from: a } of via.get(y) || []) if (!onWay.has(a)) { onWay.add(a); back.push(a); }
			}
			const firsts = (children.get(x) || []).map((e) => e.to).filter((y) => onWay.has(y));
			if (new Set(firsts).size === 1) next = firsts[0];
		}
		// The payoff as the line names it: which quest gives it is the record's business only through of and next.
		const { y: _y, ...shown } = pay;
		result.set(x, { step: sx.step, of, pay: shown, next });
	}
	// A breadcrumb (BreadcrumbForQuestId) is no step, but it's the errand that sends you to one: it leads
	// where the quest it points at leads, with no step (a player can start the chain without it).
	for (const b of ctx.ids) {
		const to = Q[b].crumb;
		if (!to || result.get(b) || !result.get(to) || !stepOf(b)) continue;
		result.set(b, { step: null, of: null, pay: result.get(to).pay, next: to });
	}
	return result;
}

/** The context every profile shares: the quests, what each needs, the each-from-all groups, the payoffs. */
export function context(facts, review) {
	const Q = facts.quests;
	const inst = instancesOf(facts, review);
	const ids = Object.keys(Q).map(Number).sort((a, b) => a - b);
	const needs = new Map();
	const add = (to, from) => { if (!Q[to] || !Q[from]) return; if (!needs.has(to)) needs.set(to, []); if (!needs.get(to).includes(from)) needs.get(to).push(from); };
	const groups = new Map();
	for (const id of ids) {
		const q = Q[id];
		if (q.prev > 0) add(id, q.prev);
		if (q.next > 0) add(q.next, id);
		if (q.ex < 0) { if (!groups.has(q.ex)) groups.set(q.ex, []); groups.get(q.ex).push(id); }
	}
	for (const list of needs.values()) list.sort((a, b) => a - b);
	const payoff = new Map();
	const problems = [...inst.problems];
	for (const id of ids) {
		let map = dungeonOf(Q[id], inst);
		const fix = review.quests?.[id];
		if (fix && "dungeon" in fix) {
			if (!fix.why) problems.push(`quest ${id}: a review needs its why`);
			if ((fix.dungeon ?? null) === map) problems.push(`quest ${id}: the review says what the rules already say`);
			map = fix.dungeon ?? null;
			if (map !== null && !inst.instances.has(map)) problems.push(`quest ${id}: ${map} isn't a party or raid instance`);
		}
		if (fix && fix.skip && !fix.why) problems.push(`quest ${id}: a review needs its why`);
		if (map !== null && inst.unnamed.has(map)) problems.push(`quest ${id}: its instance ${map} has no area that names it; add one to reviewed.json`);
		else if (map !== null) payoff.set(id, map);
	}
	for (const id of Object.keys(review.quests || {})) if (!Q[id]) problems.push(`quest ${id}: reviewed but not in cmangos.json`);
	return { ids, needs, groups, payoff, inst, problems };
}

const key = (rec) => JSON.stringify(rec);

/**
 * Every quest's records: quest -> { all: record } or { class: { bit: record } } or { race: { bit: record } },
 * worked out for each race and class that can take it. One for all only when every one of them has it; a
 * class or race it leads to nothing for gets none. When a quest's records differ by both, or a class or race
 * still has two, it says less: the step and count each kept only where every one agrees, the payoff only
 * when there's one, and nothing when it leads to nothing for some.
 */
export function chains(facts, review) {
	const ctx = context(facts, review);
	if (ctx.problems.length) throw new Error("generate.mjs:\n  " + ctx.problems.join("\n  "));
	const per = new Map(); // quest -> Map("r:c" -> record)
	for (const [r, c] of pairs(facts)) {
		for (const [x, rec] of profile(facts, review, r, c, ctx)) {
			if (!per.has(x)) per.set(x, new Map());
			per.get(x).set(`${r}:${c}`, rec);
		}
	}
	const out = new Map();
	for (const [x, recs] of per) {
		if (![...recs.values()].some(Boolean)) continue; // it leads to nothing for anyone who can take it
		const distinct = new Set([...recs.values()].map(key));
		if (distinct.size === 1) { out.set(x, { all: [...recs.values()][0] }); continue; }
		const by = (pick) => {
			const m = new Map();
			for (const [k, rec] of recs) {
				const b = Number(k.split(":")[pick]);
				if (!m.has(b)) m.set(b, new Set());
				m.get(b).add(key(rec));
			}
			if ([...m.values()].some((s) => s.size > 1)) return null;
			// A class (or race) it leads to nothing for gets no record: the addon shows it no line.
			return Object.fromEntries([...m].filter(([, s]) => !s.has("null")).map(([b, s]) => [b, JSON.parse([...s][0])]));
		};
		const byClass = by(1);
		if (byClass) { out.set(x, { class: byClass }); continue; }
		const byRace = by(0);
		if (byRace) { out.set(x, { race: byRace }); continue; }
		const less = degrade([...recs.values()]);
		if (less) out.set(x, { all: less });
	}
	return out;
}

/** One record that every one of these is true to, or null: what they share, the rest unknown. */
export function degrade(recs) {
	if (recs.some((r) => !r)) return null; // it leads to nothing for some of them
	const pays = new Set(recs.map((r) => key(r.pay)));
	if (pays.size !== 1) return null;
	const same = (k) => (new Set(recs.map((r) => r[k])).size === 1 ? recs[0][k] : null);
	const step = same("step");
	return { step, of: step === null ? null : same("of"), pay: recs[0].pay, next: same("next") };
}

/** The payoffs, numbered in the order the quests name them first. */
function payoffTable(all, ctx, facts) {
	const list = [];
	const index = new Map();
	const id = (pay) => {
		const k = pay.kind === "dungeon" ? `d${pay.map}` : `i${pay.item}:${pay.more}`;
		if (!index.has(k)) {
			index.set(k, list.length + 1);
			if (pay.kind === "dungeon") {
				const inst = ctx.inst.instances.get(pay.map);
				list.push({ kind: inst.raid ? "raid" : "dungeon", area: inst.area, name: inst.name });
			} else {
				const it = facts.items[pay.item];
				list.push({ kind: "item", item: pay.item, quality: it.quality, name: it.name, more: pay.more });
			}
		}
		return index.get(k);
	};
	for (const [, recs] of all) for (const rec of Object.values(recs.all ? { all: recs.all } : (recs.class || recs.race))) id(rec.pay);
	return { list, id };
}

// A name is third-party text written into a Lua string: a quote, a backslash or a control character
// would end it and run the rest as code, and a | or a bracket would break the link the addon makes of it.
function luaString(s, what) {
	if (typeof s !== "string" || !s || /[\u0000-\u001f\u007f"\\|[\]]/.test(s)) throw new Error(`generate.mjs: ${what} has a character a Lua string or a game link can't hold as it is; refusing to write it`);
	return `"${s}"`;
}

/**
 * A record as the addon reads it: "step of payoff next", 0 for unknown; a first step adds its zone (where
 * the quest log files it, 0 for a sort), the level it needs and its own level, 1 when another quest of its
 * exclusive group can take its place (the addon doesn't offer it then), and the races and classes that
 * can take it (masks, 0 for any class), so the addon offers it only to them.
 */
function recordString(rec, x, facts, pays) {
	const parts = [rec.step ?? 0, rec.of ?? 0, pays.id(rec.pay), rec.next ?? 0];
	if (rec.step === 1) {
		const q = facts.quests[x];
		parts.push(q.zone > 0 ? q.zone : 0, q.min, q.level, q.ex > 0 ? 1 : 0, whoCan(q), q.classes || 0);
	}
	return `"${parts.join(" ")}"`;
}

/** The block, markers included, and its counts. */
export function render(facts, review) {
	const all = chains(facts, review);
	const ctx = context(facts, review);
	const pays = payoffTable(all, ctx, facts);
	const ids = [...all.keys()].sort((a, b) => a - b);
	const lines = [];
	let variants = 0;
	for (const x of ids) {
		const recs = all.get(x);
		if (recs.all) { lines.push(`\t[${x}] = ${recordString(recs.all, x, facts, pays)},`); continue; }
		variants++;
		const which = recs.class ? "class" : "race";
		const by = recs.class || recs.race;
		const inner = Object.keys(by).map(Number).sort((a, b) => a - b).map((b) => `[${b}] = ${recordString(by[b], x, facts, pays)}`).join(", ");
		lines.push(`\t[${x}] = { ${which} = { ${inner} } },`);
	}
	const payLines = pays.list.map((p, i) => (p.kind === "item"
		? `\t{ "item", ${p.item}, ${p.quality}, ${luaString(p.name, `item ${p.item}'s name`)}, ${p.more} }, -- ${i + 1}`
		: `\t{ "${p.kind}", ${p.area}, ${luaString(p.name, `area ${p.area}'s name`)} }, -- ${i + 1}`));
	const s = facts.sources;
	const dungeons = pays.list.filter((p) => p.kind === "dungeon" || p.kind === "raid").length;
	const block = [
		BEGIN,
		"-- From the emulator's quest data by generate.mjs's rules, with reviewed.json's",
		"-- corrections. Sources:",
		`--   ${s.db}`,
		`--   ${s.maps} and ${s.areas} (which areas name an instance)`,
		`--   ${s.factions} (who a quest giver offers a quest to)`,
		`--   ${s.skills} (who can equip what)`,
		`--   ${s.combos} (the races and classes the game pairs)`,
		"-- tools/quest-chains/README.md says how to refresh them.",
		`-- What a chain leads to: ${dungeons} dungeons and raids, ${pays.list.length - dungeons} rewards. { kind, area, English name },`,
		"-- { \"item\", item, quality, English name, how many other rare or better picks the class could take instead }.",
		"local PAYOFFS = {",
		...payLines,
		"}",
		`-- ${ids.length} quests that lead to one (${variants} by class or race). "step of payoff next", 0 for`,
		"-- unknown; a first step adds \"zone min level exclusive races classes\".",
		"local STEPS = {",
		...lines,
		"}",
		"C.PAYOFFS, C.STEPS = PAYOFFS, STEPS",
		END,
	].join("\n");
	return { block, count: ids.length, variants, payoffs: pays.list.length, all };
}

// The file with its block replaced by `block`.
export function splice(lua, block) {
	const a = lua.indexOf(BEGIN);
	const b = lua.indexOf(END, a);
	if (a < 0 || b < 0) throw new Error(`generate.mjs: no generated block in ${LUA}`);
	return lua.slice(0, a) + block + lua.slice(b + END.length);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
	const { facts, review } = load();
	const show = process.argv.indexOf("--show");
	if (show > 0) {
		const x = Number(process.argv[show + 1]);
		const ctx = context(facts, review);
		for (const [r, c] of pairs(facts)) {
			const rec = profile(facts, review, r, c, ctx).get(x);
			if (rec !== undefined) console.log(`race ${r} class ${c}: ${rec ? JSON.stringify(rec) : "leads to nothing"}`);
		}
		console.log(JSON.stringify(chains(facts, review).get(x) || null));
		process.exit(0);
	}
	const lua = fs.readFileSync(LUA, "utf8");
	const r = render(facts, review);
	const next = splice(lua, r.block);
	if (process.argv.includes("--check")) {
		if (next !== lua) {
			console.error("generate.mjs: Chains.lua's quest chains are out of date; run node tools/quest-chains/generate.mjs");
			process.exit(1);
		}
		console.log("generate.mjs: Chains.lua is up to date");
	} else {
		fs.writeFileSync(LUA, next);
		console.log(`generate.mjs: ${r.count} quests (${r.variants} by class or race), ${r.payoffs} payoffs -> ${LUA}`);
	}
}
