#!/usr/bin/env node
// gen-prompts: the prompt pack from its one source (public BYOK PRD §6.2 "Skill", DB19, RT-2).
//
//   node tools/gen-prompts.mjs           write the outputs that changed
//   node tools/gen-prompts.mjs --check   write nothing; exit 1 if an output is out of date
//
// prompts/companion.md is the single source of the companion's prompt, and makes one output:
//   bridge/byok/runtime/pack.md    the prompt pack (runtime/pack.mjs)
//
// Source syntax, one directive per line (the whole line):
//   <!-- include PATH from="HEADING" demote=N omit="TEXT" -->
//                                    a repo file's lines from the line equal to HEADING (else all),
//                                    Markdown headings outside code fences N levels deeper, lines
//                                    containing TEXT left out
//   <!--# ... -->                    a note for editors of the source (may span lines); never output
// Everything else is the pack's. {{code.X}} is replaced by a number or list from the code that
// enforces it (bridge/app/render.mjs, MAP_LIMITS in bridge/app/map-protocol.mjs, MAP_BYTES_MAX in
// bridge/app/map.mjs), so the prompt can't drift from the validators. {{name}} is left for pack.mjs
// (the persona's name, DB16).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as render from '../bridge/app/render.mjs';
import { MAP_BYTES_MAX } from '../bridge/app/map.mjs';
import { MAP_LIMITS } from '../bridge/app/map-protocol.mjs';

export const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const SOURCE = 'prompts/companion.md';
export const PACK_BANNER = '<!-- Generated by tools/gen-prompts.mjs from prompts/companion.md: edit the source, then run it. -->';
export const PACK = 'bridge/byok/runtime/pack.md';
const RUNTIME = ['name']; // the {{…}} left for pack.mjs

/** The numbers and lists the prompt quotes, from the code that enforces them. */
export function codeValues() {
  return {
    RECORD_TEXT_MAX: render.RECORD_TEXT_MAX,
    SUMMARY_MAX: render.SUMMARY_MAX,
    CHIPS_MAX: render.CHIPS_MAX,
    CHIP_CHARS: render.CHIP_CHARS,
    REFS_MAX: render.REFS_MAX,
    WEIGHT_KEYS: render.WEIGHT_KEYS,
    WEIGHT_MAX: render.WEIGHT_MAX,
    MAP: MAP_LIMITS,
    MAP_KB: MAP_BYTES_MAX / 1024, // what a slot always carries (DREW-SY-04)
  };
}

/** 12000 → "12,000"; a list → "a, b, c". */
export function formatValue(v, name) {
  if (Number.isInteger(v)) return String(v).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  if (Array.isArray(v) && v.every(x => typeof x === 'string')) return v.join(', ');
  throw new Error(`{{code.${name}}} is not a whole number or a list of strings`);
}

const INCLUDE = /^<!-- include (\S+)((?: [a-z]+=(?:"[^"]*"|\S+))*) -->$/;
const ATTR = / ([a-z]+)=(?:"([^"]*)"|(\S+))/g;

/** A file's lines for an include: from a heading, headings demoted outside fences, some lines omitted. */
export function includeLines(text, { from = null, demote = 0, omit = null } = {}) {
  let lines = String(text).replace(/\r\n?/g, '\n').replace(/\n$/, '').split('\n');
  if (from !== null) {
    const i = lines.indexOf(from);
    if (i < 0) throw new Error(`include: no line "${from}"`);
    lines = lines.slice(i);
  }
  if (omit) lines = lines.filter(l => !l.includes(omit));
  let fenced = false;
  return lines.map((l) => {
    if (/^\s*(```|~~~)/.test(l)) fenced = !fenced;
    return !fenced && demote > 0 && /^#{1,6} /.test(l) ? '#'.repeat(demote) + l : l;
  });
}

/**
 * The source rendered: directives applied, {{code.X}} filled in.
 * readFile(relativePath) gives an included file's text; runtime lists the {{…}} left as they are.
 */
export function renderSource(source, { code = codeValues(), readFile = f => fs.readFileSync(path.join(REPO, f), 'utf8'), runtime = [] } = {}) {
  const out = [];
  let note = false;
  const lines = String(source).replace(/\r\n?/g, '\n').split('\n');
  lines.forEach((line, i) => {
    const where = `${SOURCE}:${i + 1}`;
    if (note) { if (line.includes('-->')) note = false; return; }
    if (line.startsWith('<!--#')) { note = !line.includes('-->'); return; }
    if (/^<!-- \/?variant\b/.test(line)) throw new Error(`${where}: there are no variants (one output, the pack)`);
    let m;
    if ((m = line.match(INCLUDE))) {
      const opts = {};
      for (const a of m[2].matchAll(ATTR)) opts[a[1]] = a[2] ?? a[3];
      out.push(...includeLines(readFile(m[1]), { from: opts.from ?? null, demote: Number(opts.demote || 0), omit: opts.omit || null }));
      return;
    }
    out.push(line);
  });
  if (note) throw new Error(`${SOURCE}: a <!--# note is never closed`);
  const text = out.join('\n').replace(/\{\{code\.([A-Za-z_]+)(?:\.([A-Za-z_]+))?\}\}/g, (_, a, b) => {
    const v = b ? code[a]?.[b] : code[a];
    if (v === undefined) throw new Error(`unknown placeholder {{code.${a}${b ? `.${b}` : ''}}}`);
    return formatValue(v, b ? `${a}.${b}` : a);
  });
  for (const m of text.matchAll(/\{\{([^}]*)\}\}/g)) {
    if (!runtime.includes(m[1])) throw new Error(`unknown placeholder {{${m[1]}}}`);
  }
  return text;
}

/** What the pack should hold, and whether the file on disk differs: [{file, text, stale}]. */
export function build({ repo = REPO } = {}) {
  const source = fs.readFileSync(path.join(repo, SOURCE), 'utf8');
  const readFile = f => fs.readFileSync(path.join(repo, f), 'utf8');
  const text = `${PACK_BANNER}\n${renderSource(source, { readFile, runtime: RUNTIME })}`;
  let current = null;
  try { current = fs.readFileSync(path.join(repo, PACK), 'utf8'); } catch (e) { if (e.code !== 'ENOENT') throw e; }
  return [{ file: PACK, text, stale: current !== text }];
}

export function run(argv, { stdout = process.stdout, stderr = process.stderr, repo = REPO } = {}) {
  const check = argv.includes('--check');
  const bad = argv.find(a => a !== '--check');
  if (bad) { stderr.write(`unknown argument ${bad}\nusage: gen-prompts.mjs [--check]\n`); return 2; }
  let outs;
  try { outs = build({ repo }); } catch (e) { stderr.write(`gen-prompts: ${e.message}\n`); return 2; }
  const stale = outs.filter(o => o.stale);
  if (check) {
    for (const o of stale) stderr.write(`out of date: ${o.file} (run node tools/gen-prompts.mjs)\n`);
    if (!stale.length) stdout.write('prompts up to date\n');
    return stale.length ? 1 : 0;
  }
  for (const o of stale) {
    fs.mkdirSync(path.dirname(path.join(repo, o.file)), { recursive: true });
    fs.writeFileSync(path.join(repo, o.file), o.text);
    stdout.write(`wrote ${o.file}\n`);
  }
  if (!stale.length) stdout.write('prompts up to date\n');
  return 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === fs.realpathSync(process.argv[1])) {
  process.exitCode = run(process.argv.slice(2));
}
