-- Paste.lua: Copy and Paste, Bones with any AI and nothing to install.
--
-- An addon can't reach the network (docs/ARCHITECTURE.md "The sandbox"), so
-- without the NeverQuestAlone app the player carries the words: a message
-- goes into a box, with Bones's instructions and the game data, to copy into
-- ChatGPT, Claude or any other AI; the AI's reply, pasted back, is read here
-- as the app reads it (bridge/app/render.mjs, bridge/protocol.js): its TL;DR
-- and its wowmap, wowchips, wowrefs and wowweights blocks. It then goes the
-- way a reply from the app goes (Chats.ApplyRecord, NQAMap.Sync), so the
-- window, the HUD, routes, pins and tooltip verdicts all work the same.
--
-- It's the way for an install no app has answered yet (NQADB.linked, set
-- by Transport.lua when one does), and for anyone who picks it in Settings
-- (settings.replies = "paste"). docs/ADDON-FIRST.md has the whole design.
--
-- Nothing pasted runs: it's read as text and data (no loadstring), under the
-- app's own limits, and every | is doubled before it's shown.

local _, ns = ...
local P = {}
ns.Paste = P
local R = ns.R

local PASTE_MAX = 60000 -- bytes of one paste that are read
local JSON_DEPTH = 16
local AUTO_APPLY = 2 -- bytes arriving at once in step 1: a paste there (a key adds one), moved to the reply box and read
-- [code health AD-13] The app's own limits, map limits and distance claims, made from
-- the bridge (they were copied by hand here); tests/paste_test.mjs holds them equal.
-- AD-13: generated by tests/helpers/paste-lua.mjs from bridge/app/render.mjs and bridge/protocol.js; do not edit by hand.
local TEXT_MAX = 12000 -- bytes of a reply's text (RECORD_TEXT_MAX)
local SUMMARY_MAX = 160 -- characters of the TL;DR (SUMMARY_MAX)
local CHIPS_MAX, CHIP_CHARS, REFS_MAX = 3, 60, 8
-- A pasted route is held to what a route from the app is (MAP_LIMITS, MAP_KINDS).
local MAP = { layers = 12, pointsPerLayer = 400, totalPoints = 1500, label = 80, title = 80, note = 200, quests = 6, layerNotes = 6000, mapNotes = 16000, layerName = 32, mapIdMax = 99999 }
local KINDS = { ore = true, herb = true, quest = true, turnin = true, kill = true, loot = true, object = true, explore = true, npc = true, trainer = true, vendor = true, dungeon = true, flight = true, poi = true }
-- The distance claims a stop's note loses, and the words around them (DISTANCE_CLAIMS and its sets).
local CLAIMS = {
	DISTANCE_CLAIMS = {
		"from you", "from here", "near you", "next to you", "beside you", "behind you", "in front of you",
		"ahead of you", "north/south/east/west/northeast/northwest/southeast/southwest/left/right of you", "of you",
		"right by you", "close/closer/closest/nearer/nearest to you", "where you are", "where you stand",
		"you're standing", "you are standing", "right here",
		"it's/he's/she's/they're/that's right/just/very/really/so? nearby",
		"it's/he's/she's/they're/that's right/just/very/really/so? close$",
		"closest/nearest stop/stops/one/ones/first/quest/quests/turn/pickup/objective/objectives/point/spot",
		"closest/nearest$", "few steps~", "few yards~", "a/one step away~", "steps away~", "short walk/run/ride~",
		"stone's throw~", "just ahead~", "around the corner~", "# yd/yds/yard/yards~", "#yd~", "close by$", "^nearby$",
	},
	MEASURED_FROM = { "of", "from", "past", "beyond", "behind", "beside", "along", "across", "toward", "towards", "by", "near" },
	SELF_WORDS = { "you", "your", "here", "where" },
	COMPASS = { "north", "south", "east", "west", "northeast", "northwest", "southeast", "southwest", "northern", "southern", "eastern", "western" },
	CLAIM_AFTER = { "away", "ahead" },
	CLAIM_BEFORE = { "just", "right", "a", "an", "the", "only", "about", "roughly", "very", "so", "really" },
	HANGING = {
		"just", "right", "a", "an", "the", "only", "about", "roughly", "very", "so", "really", "is", "are", "was",
		"were", "it", "it's", "he's", "she's", "they're", "that's", "there's", "that", "which", "who", "and", "or",
		"but",
	},
	NOT_CONTENT = {
		"just", "right", "a", "an", "the", "only", "about", "roughly", "very", "so", "really", "is", "are", "was",
		"were", "it", "it's", "he's", "she's", "they're", "that's", "there's", "that", "which", "who", "and", "or",
		"but", "then", "if", "be", "its", "he", "she", "they", "them", "him", "her", "his", "their", "this", "these",
		"those", "there", "here", "you", "your", "you're", "yours", "i", "i'm", "we", "we're", "us", "me", "my", "to",
		"of", "from", "by", "at", "in", "on", "for", "with", "up", "down", "over", "into", "onto", "quite", "pretty",
		"also", "already", "still", "now", "first", "one", "ones", "where", "as", "away", "ahead", "close", "closer",
		"closest", "near", "nearer", "nearest", "nearby", "far", "steps", "step", "yards", "yard", "yd", "yds", "few",
	},
	CLAUSE_SEPS = { " -- ", " - ", " \226\128\148 ", " \226\128\147 ", "\226\128\148", ", ", "; ", ": " },
}
-- AD-13: the end of the generated block.
-- The map's epoch for routes read here. The app keeps its own; once it answers,
-- its set replaces these (NQAMap.Sync takes another epoch whole).
local EPOCH = "paste"
-- The first line of every message this file builds, so a paste of the message
-- itself (not the AI's reply) is caught.
P.MARK = "(Message from the NeverQuestAlone addon for World of Warcraft: Forever)"

-- The companion's name in our own words (STYLE.md §11): ns.P puts the
-- player's name for Bones in, and leaves "NeverQuestAlone" alone. Every line
-- of ours that names Bones goes through it.
function P.Named(s)
	if type(ns.P) == "function" then return ns.P(s) end
	return s
end

-- How the message for the AI starts, with the companion's name in.
local function Instructions() return P.Named(P.INSTRUCTIONS) end

---------------------------------------------------------------------------
-- Small text helpers
---------------------------------------------------------------------------

local Trim, Pipes = ns.Trim, ns.Escape -- (Store.lua; code health AD-14)

-- Characters in UTF-8 text (continuation bytes don't count), as the app counts them.
local function Chars(s) return select(2, tostring(s or ""):gsub("[^\128-\191]", "")) end

-- The first n characters of UTF-8 text.
local function CutChars(s, n)
	s = tostring(s or "")
	local count, i = 0, 1
	while i <= #s do
		local b = s:byte(i)
		if b < 128 or b >= 192 then
			if count == n then return s:sub(1, i - 1) end
			count = count + 1
		end
		i = i + 1
	end
	return s
end

-- At most max characters; past that, cut at a word and end with "…" (the app's rule).
local function Shorten(s, max)
	if Chars(s) <= max then return s end
	local cut = CutChars(s, max - 1)
	cut = cut:gsub("%s+%S*$", "")
	return cut .. "…"
end

local function Lines(s)
	local out = {}
	for line in (tostring(s or "") .. "\n"):gmatch("([^\n]*)\n") do out[#out + 1] = line end
	return out
end

---------------------------------------------------------------------------
-- JSON, read (the addon's writer is Companion.lua's). Pasted text is data: a
-- small reader with a depth limit that never raises, and arrays marked so an
-- empty [] is still one.
---------------------------------------------------------------------------

local ARRAY = setmetatable({}, { __mode = "k" })
P.IsArray = function(t) return type(t) == "table" and ARRAY[t] == true end

local function Utf8(cp)
	if cp < 0x80 then return string.char(cp) end
	if cp < 0x800 then return string.char(0xC0 + math.floor(cp / 0x40), 0x80 + cp % 0x40) end
	if cp < 0x10000 then
		return string.char(0xE0 + math.floor(cp / 0x1000), 0x80 + math.floor(cp / 0x40) % 0x40, 0x80 + cp % 0x40)
	end
	return string.char(0xF0 + math.floor(cp / 0x40000), 0x80 + math.floor(cp / 0x1000) % 0x40,
		0x80 + math.floor(cp / 0x40) % 0x40, 0x80 + cp % 0x40)
end

local ESCAPES = { ['"'] = '"', ["\\"] = "\\", ["/"] = "/", b = "\b", f = "\f", n = "\n", r = "\r", t = "\t" }

-- Returns true, value (value may be nil for null) or false, why.
function P.JSON(s)
	s = tostring(s or "")
	local i, n, depth = 1, #s, 0
	local function fail(why) error({ json = why }, 0) end
	local function skip() i = s:find("[^ \t\r\n]", i) or n + 1 end
	local value
	local function str()
		i = i + 1
		local out = {}
		while true do
			local j = s:find('["\\%c]', i)
			if not j then fail("a string doesn't end") end
			out[#out + 1] = s:sub(i, j - 1)
			local c = s:sub(j, j)
			if c == '"' then
				i = j + 1
				return table.concat(out)
			end
			if c ~= "\\" then fail("a control character in a string") end
			local e = s:sub(j + 1, j + 1)
			if e == "u" then
				local hex = s:match("^%x%x%x%x", j + 2)
				if not hex then fail("a bad \\u escape") end
				local cp = tonumber(hex, 16)
				i = j + 6
				if cp >= 0xD800 and cp <= 0xDBFF then
					local lo = s:match("^\\u(%x%x%x%x)", i)
					local low = lo and tonumber(lo, 16)
					if low and low >= 0xDC00 and low <= 0xDFFF then
						cp = 0x10000 + (cp - 0xD800) * 0x400 + (low - 0xDC00)
						i = i + 6
					else
						cp = 0xFFFD
					end
				elseif cp >= 0xDC00 and cp <= 0xDFFF then
					cp = 0xFFFD
				end
				out[#out + 1] = Utf8(cp)
			else
				local v = ESCAPES[e]
				if not v then fail("a bad escape") end
				out[#out + 1] = v
				i = j + 2
			end
		end
	end
	local function num()
		local m = s:match("^-?%d+%.?%d*[eE][-+]?%d+", i) or s:match("^-?%d+%.?%d*", i)
		local v = m and tonumber(m)
		if not v then fail("a bad number") end
		i = i + #m
		return v
	end
	function value()
		skip()
		local c = s:sub(i, i)
		if c == "{" or c == "[" then
			depth = depth + 1
			if depth > JSON_DEPTH then fail("too deep") end
			i = i + 1
			local t, close, k = {}, c == "{" and "}" or "]", 0
			skip()
			if s:sub(i, i) == close then
				i = i + 1
			else
				while true do
					skip()
					if c == "{" then
						if s:sub(i, i) ~= '"' then fail("a key isn't a string") end
						local key = str()
						skip()
						if s:sub(i, i) ~= ":" then fail("a key has no value") end
						i = i + 1
						t[key] = value()
					else
						local v = value()
						if v ~= nil then
							k = k + 1
							t[k] = v
						end
					end
					skip()
					local d = s:sub(i, i)
					i = i + 1
					if d == close then break end
					if d ~= "," then fail("a list isn't separated by commas") end
				end
			end
			if c == "[" then ARRAY[t] = true end
			depth = depth - 1
			return t
		elseif c == '"' then
			return str()
		elseif s:sub(i, i + 3) == "true" then
			i = i + 4
			return true
		elseif s:sub(i, i + 4) == "false" then
			i = i + 5
			return false
		elseif s:sub(i, i + 3) == "null" then
			i = i + 4
			return nil
		elseif c:match("^[-%d]$") then
			return num()
		end
		fail("an unexpected character")
	end
	local ok, v = pcall(function()
		local r = value()
		skip()
		if i <= n then fail("text after the value") end
		return r
	end)
	if ok then return true, v end
	return false, type(v) == "table" and v.json or "unreadable"
end

---------------------------------------------------------------------------
-- Markdown to the window's text, as the app renders a reply
-- (bridge/app/render.mjs markdownToWow): headings gold, bullets •, code gray
-- and indented, tables as rows; every | doubled.
---------------------------------------------------------------------------

local GOLD, GRAY, CLOSE = "|cffffd100", "|cffa0a0a0", "|r"

-- A pair of marks (** __ ~~) around text that starts and ends with a non-space.
-- [code health AD-02] A closing mark is one after a non-space, wherever the opener is:
-- once an opener finds none, no later opener can (each looks in less of the same
-- text), so the rest goes as it is. One pass, where a 60 KB line of unclosed marks
-- looked again from every opener and froze the client for seconds.
local function Pair(s, mark)
	local out, i, w = {}, 1, #mark
	while true do
		local a = s:find(mark, i, true)
		if not a then break end
		local b, inner = a + w, nil
		if s:sub(a + w, a + w):match("%S") then
			b = s:find(mark, a + w + 1, true)
			while b and not s:sub(b - 1, b - 1):match("%S") do b = s:find(mark, b + 1, true) end
			if not b then break end
			inner = s:sub(a + w, b - 1)
		end
		if inner then
			out[#out + 1] = s:sub(i, a - 1) .. inner
			i = b + w
		else
			out[#out + 1] = s:sub(i, a + w - 1)
			i = a + w
		end
	end
	out[#out + 1] = s:sub(i)
	return table.concat(out)
end

-- One-mark emphasis (* or _): not after a word character or the mark, not
-- before one, no mark or line break inside.
local function Single(s, mark)
	local word = mark == "*" and "[%w_%*]" or "[%w_]"
	local out, i = {}, 1
	while true do
		local a = s:find(mark, i, true)
		if not a then break end
		local before = a > 1 and s:sub(a - 1, a - 1) or ""
		local b = s:find(mark, a + 1, true)
		local inner = b and s:sub(a + 1, b - 1)
		if inner and inner ~= "" and not before:match(word) and inner:match("^%S") and inner:match("%S$")
			and not inner:find("\n", 1, true) and not s:sub(b + 1, b + 1):match("[%w_]") then
			out[#out + 1] = s:sub(i, a - 1) .. inner
			i = b + 1
		else
			out[#out + 1] = s:sub(i, a)
			i = a + 1
		end
	end
	out[#out + 1] = s:sub(i)
	return table.concat(out)
end

-- Inline markdown to plain text (no escapes added).
local function InlinePlain(s)
	s = tostring(s or "")
	s = s:gsub("!%[([^%]]*)%]%(([^%)%s]+)[^%)]*%)", function(alt, url)
		return "[image" .. (alt ~= "" and (": " .. alt) or "") .. "] (" .. url .. ")"
	end)
	s = s:gsub("%[([^%]]+)%]%(([^%)%s]+)[^%)]*%)", function(t, url) return t == url and url or (t .. " (" .. url .. ")") end)
	s = s:gsub("<(https?://[^>%s]+)>", "%1")
	s = s:gsub("`([^`]+)`", "%1")
	s = Pair(s, "**")
	s = Pair(s, "__")
	s = Single(s, "*")
	s = Single(s, "_")
	s = Pair(s, "~~")
	return s
end
P.InlinePlain = InlinePlain

local function TableRow(l) return l:match("^%s*|.*|%s*$") ~= nil end
local function TableSep(l)
	local body = Trim(l):gsub("^|", ""):gsub("|$", "")
	if body == "" then return false end
	for cell in (body .. "|"):gmatch("([^|]*)|") do
		if not cell:match("^%s*:?%-%-%-+:?%s*$") then return false end
	end
	return true
end
local function Cells(l)
	local out = {}
	local body = Trim(l):gsub("^|", ""):gsub("|$", "")
	for cell in (body .. "|"):gmatch("([^|]*)|") do out[#out + 1] = InlinePlain(Trim(cell)) end
	return out
end

-- The one sentence under a table (the window can't draw tables).
P.TABLE_NOTE = "(A table doesn't fit here, so its rows follow. Your AI's page shows it whole.)"

function P.Markdown(md)
	local lines = Lines(tostring(md or ""):gsub("\r\n?", "\n"))
	local out, inCode, i = {}, false, 1
	while i <= #lines do
		local line = lines[i]
		if line:match("^%s*```") or line:match("^%s*~~~") then
			inCode = not inCode
		elseif inCode then
			out[#out + 1] = line:match("%S") and ("    " .. GRAY .. Pipes(line) .. CLOSE) or ""
		elseif TableRow(line) and lines[i + 1] and TableSep(lines[i + 1]) then
			local rows = { Cells(line) }
			i = i + 1
			while lines[i + 1] and TableRow(lines[i + 1]) do
				i = i + 1
				rows[#rows + 1] = Cells(lines[i])
			end
			out[#out + 1] = GRAY .. Pipes(P.TABLE_NOTE) .. CLOSE
			for r = 1, math.min(#rows, 6) do out[#out + 1] = Pipes(table.concat(rows[r], " · ")) end
			if #rows > 6 then
				local more = #rows - 6
				out[#out + 1] = GRAY .. Pipes(more == 1 and "… 1 more row" or string.format("… %d more rows", more)) .. CLOSE
			end
		else
			local hashes, head = line:match("^%s*(#+)%s+(.-)%s*#*%s*$")
			local bare = line:gsub("%s", "")
			local indent, mark, rest = line:match("^(%s*)[-*+]%s+%[([ xX])%]%s+(.*)$")
			local bIndent, bullet = line:match("^(%s*)[-*+]%s+(.*)$")
			local quote = line:match("^%s*>%s?(.*)$")
			if hashes and #hashes <= 6 then
				out[#out + 1] = GOLD .. Pipes(InlinePlain(head)) .. CLOSE
			elseif #bare >= 3 and (bare:match("^%-+$") or bare:match("^%*+$") or bare:match("^_+$")) then
				out[#out + 1] = "———"
			elseif indent then
				out[#out + 1] = string.rep("  ", math.floor(#indent / 2)) .. (mark == " " and "☐" or "☑") .. " " .. Pipes(InlinePlain(rest))
			elseif bIndent then
				out[#out + 1] = string.rep("  ", math.floor(#bIndent / 2)) .. "• " .. Pipes(InlinePlain(bullet))
			elseif quote then
				out[#out + 1] = GRAY .. "  " .. Pipes(InlinePlain(quote)) .. CLOSE
			else
				out[#out + 1] = Pipes(InlinePlain(line))
			end
		end
		i = i + 1
	end
	local s = table.concat(out, "\n"):gsub("\n\n\n+", "\n\n")
	return Trim(s)
end

---------------------------------------------------------------------------
-- A reply's parts: its TL;DR (protocol.js splitSummary) and the blocks the
-- game reads, each a fenced block on lines of its own.
---------------------------------------------------------------------------

-- The text after the last line that starts with a TL;DR marker ("TL;DR:",
-- "**TL;DR:**", "## TL;DR", "TLDR"), else "".
function P.SplitSummary(text)
	local lines = Lines(Trim(text))
	for k = #lines, 1, -1 do
		local marker = lines[k]:match("^[ \t]*#*[ \t]*[%*_]*[ \t]*[Tt][Ll];?[Dd][Rr][ \t]*:?[ \t]*[%*_]*[ \t]*:?[ \t]*")
		if marker then
			local rest = { lines[k]:sub(#marker + 1) }
			for j = k + 1, #lines do rest[#rest + 1] = lines[j] end
			return Trim(table.concat(rest, "\n"))
		end
	end
	return ""
end

local function FirstSentence(plain)
	for _, line in ipairs(Lines(plain)) do
		if line:match("%S") then
			line = Trim(line)
			local s = line:match("^(.-[%.!%?])%s") or line:match("^(.-[%.!%?])$") or line
			return Shorten(Trim(s), SUMMARY_MAX)
		end
	end
	return ""
end

local BLOCKS = { wowmap = true, wowchips = true, wowrefs = true, wowweights = true }

-- Take the blocks out: returns the text left and { { kind, body }, ... }. A
-- block's fence is a line of its own; an AI page's Copy can drop the last
-- closing fence, so an unclosed block runs to the end. A line that is a bare
-- map command (the fence lost when the reply was copied as shown on the page,
-- not with its Copy button) still draws.
local function TakeBlocks(s)
	local lines, keep, found = Lines(s), {}, {}
	local i = 1
	while i <= #lines do
		local line = lines[i]
		local kind = line:match("^%s*```+%s*(%a+)%s*$")
		kind = kind and kind:lower()
		if kind and BLOCKS[kind] then
			local body, j = {}, i + 1
			while j <= #lines and not lines[j]:match("^%s*```+%s*$") do
				body[#body + 1] = lines[j]
				j = j + 1
			end
			found[#found + 1] = { kind = kind, body = table.concat(body, "\n") }
			keep[#keep + 1] = "" -- where the block was, a paragraph break (as the app leaves it)
			i = j + 1
		elseif line:match('^%s*{%s*"op"%s*:') then
			found[#found + 1] = { kind = "wowmap", body = line }
			i = i + 1
		else
			keep[#keep + 1] = line
			i = i + 1
		end
	end
	return table.concat(keep, "\n"), found
end

-- Suggested replies: plain text, no |, one line each, at most 60 characters.
local function Chips(src)
	local ok, j = P.JSON(src)
	local list = {}
	if ok and P.IsArray(j) then
		list = j
	else
		for _, l in ipairs(Lines(src)) do
			list[#list + 1] = (l:gsub("^%s*[-*]%s+", ""):gsub("^%s*\226\128\162%s+", ""):gsub("^%s*%d+[.)]%s+", ""))
		end
	end
	local out, seen = {}, {}
	for _, s in ipairs(list) do
		if type(s) == "string" then
			local t = Trim(InlinePlain(s):gsub("|", ""):gsub("%s+", " "))
			t = Shorten(t, CHIP_CHARS)
			if t ~= "" and not seen[t] then
				seen[t] = true
				out[#out + 1] = t
			end
			if #out >= CHIPS_MAX then break end
		end
	end
	return #out > 0 and out or nil
end

local REF_KEYS = { q = "q", quest = "q", quests = "q", i = "i", item = "i", items = "i", s = "s", spell = "s", spells = "s" }
local REF_ORDER = { "q", "quest", "quests", "i", "item", "items", "s", "spell", "spells" }

local function Id(v)
	if type(v) == "string" and v:match("^%d+$") then v = tonumber(v) end
	if type(v) == "number" and v == math.floor(v) and v > 0 and v < 2147483647 then return v end
end

-- Game references: whole ids, 8 of each kind at most.
local function Refs(src)
	local ok, j = P.JSON(src)
	local out, any = {}, false
	local function add(k, v)
		local id = Id(v)
		if not id then return end
		out[k] = out[k] or {}
		for _, x in ipairs(out[k]) do
			if x == id then return end
		end
		if #out[k] < REFS_MAX then
			out[k][#out[k] + 1] = id
			any = true
		end
	end
	if ok and type(j) == "table" and not P.IsArray(j) then
		local lower = {}
		for k, v in pairs(j) do
			if type(k) == "string" then lower[k:lower()] = v end
		end
		for _, key in ipairs(REF_ORDER) do
			local v = lower[key]
			if type(v) == "table" then
				for _, x in ipairs(v) do add(REF_KEYS[key], x) end
			elseif v ~= nil then
				add(REF_KEYS[key], v)
			end
		end
	else
		for _, line in ipairs(Lines(src)) do
			local word, ids = Trim(line):match("^(%a+)%s*[:=]?%s*([%d,%s]+)$")
			local kind = word and REF_KEYS[word:lower()]
			if kind then
				for x in ids:gmatch("%d+") do add(kind, x) end
			end
		end
	end
	return any and out or nil
end

-- Stat weights under the keys the addon knows, finite numbers under 100.
local function Weights(src)
	local ok, j = P.JSON(src)
	if not ok or type(j) ~= "table" or P.IsArray(j) then return nil end
	local out, any = {}, false
	for k, v in pairs(j) do
		local key = type(k) == "string" and k:lower() or nil
		if key and ns.WEIGHT_KEYS[key] and type(v) == "number" and v == v and v > -100 and v < 100 then
			out[key] = v
			any = true
		end
	end
	return any and out or nil
end

-- Map commands from a wowmap block: one value (an object or a list), else one per line.
local function MapCommands(src, into, notes)
	local ok, v = P.JSON(Trim(src))
	if ok and type(v) == "table" then
		if P.IsArray(v) then
			for _, c in ipairs(v) do into[#into + 1] = c end
		else
			into[#into + 1] = v
		end
		return
	end
	for _, line in ipairs(Lines(src)) do
		if line:match("%S") then
			local lok, c = P.JSON(line)
			if lok and c ~= nil then into[#into + 1] = c else notes[#notes + 1] = "unreadable wowmap line" end
		end
	end
end

---------------------------------------------------------------------------
-- Map commands, checked and applied as the app applies them
-- (protocol.js validateMapCommand, applyMapCommands).
---------------------------------------------------------------------------

local function CleanText(v, max)
	if type(v) ~= "string" and type(v) ~= "number" then return "" end
	local s = tostring(v):gsub("[%c|]", " "):gsub("%s+", " ")
	return ns.Utf8Cut(Trim(s), max)
end

-- A stop's note without its distance and proximity claims (protocol.js
-- dropDistanceClaims and DISTANCE_CLAIMS: the same rule, the same list). The
-- HUD shows the stop's live distance above the note; a note that says how far
-- or how close the stop is ("Closest stop, a few steps from you.") was true
-- when the route was planned and goes stale as the player moves. In a clause
-- that makes such a claim only the claim's own words go (what the list
-- matched, a trailing "away" or "ahead", a leading "just", "right", "a" and
-- the like, an "is" or "it's" left hanging at the clause's edge); the clause
-- goes whole only when nothing but stop words is left in it. A note with no
-- claim comes back unchanged, one with nothing else comes back "". A clause
-- with a compass point in it stays, unless the point is of the player ("west
-- of you"). Entries: words in order, whole, after a clause is lowercased and
-- cut to letters, digits and apostrophes; a/b either word, ? optional, # a
-- number, #yd a number run into its unit, ^ the clause's start, $ its end, ~ a
-- distance that stays when the clause says what it's measured from. The list and
-- the words below are protocol.js's own (CLAIMS, the generated block at the top).
P.DISTANCE_CLAIMS = CLAIMS.DISTANCE_CLAIMS
do
	local function Set(list)
		local t = {}
		for _, w in ipairs(list) do t[w] = true end
		return t
	end
	local MEASURED_FROM = Set(CLAIMS.MEASURED_FROM)
	local SELF_WORDS = Set(CLAIMS.SELF_WORDS)
	local COMPASS = Set(CLAIMS.COMPASS)
	-- A claim's own words around what the list matched: after it, and before it.
	local CLAIM_AFTER = Set(CLAIMS.CLAIM_AFTER)
	local CLAIM_BEFORE = Set(CLAIMS.CLAIM_BEFORE)
	-- Words left hanging at a clause's edge once a claim there is gone ("Hezrul is", "it's").
	local HANGING = Set(CLAIMS.HANGING)
	-- What isn't an instruction: stop words and the claims' own vocabulary (numbers neither).
	local NOT_CONTENT = Set(CLAIMS.NOT_CONTENT)
	-- " — ", " – " and "—" among them (UTF-8).
	local SEPS = CLAIMS.CLAUSE_SEPS
	local RULES = {}
	for _, entry in ipairs(P.DISTANCE_CLAIMS) do
		local e, rule = entry, { slots = {} }
		if e:sub(1, 1) == "^" then rule.first, e = true, e:sub(2) end
		if e:sub(-1) == "$" then rule.last, e = true, e:sub(1, -2) elseif e:sub(-1) == "~" then rule.near, e = true, e:sub(1, -2) end
		for w in e:gmatch("%S+") do
			local slot = { alts = {} }
			if w:sub(-1) == "?" then slot.opt, w = true, w:sub(1, -2) end
			if w == "#" then slot.num = true
			elseif w == "#yd" then slot.unit = true
			else for a in w:gmatch("[^/]+") do slot.alts[a] = true end end
			rule.slots[#rule.slots + 1] = slot
		end
		RULES[#RULES + 1] = rule
	end

	-- Bytes of the word character at i: an ASCII letter, digit or ', or a curly apostrophe (3); else 0.
	local function WordChar(s, i)
		if s:find("^[A-Za-z0-9']", i) then return 1 end
		local t = s:sub(i, i + 2)
		if t == "\226\128\152" or t == "\226\128\153" then return 3 end
		return 0
	end

	-- A clause's words, where they are in it (s and e, the first and last byte).
	local function Tokens(s)
		local out, i = {}, 1
		while i <= #s do
			if WordChar(s, i) > 0 then
				local st, buf = i, {}
				while i <= #s do
					local l = WordChar(s, i)
					if l == 0 then break end
					buf[#buf + 1] = l == 3 and "'" or s:sub(i, i)
					i = i + l
				end
				local w = table.concat(buf):lower():gsub("^'+", ""):gsub("'+$", "")
				if w ~= "" then out[#out + 1] = { s = st, e = i - 1, w = w } end
			else
				i = i + 1
			end
		end
		return out
	end

	-- Where the slots from k on, matched from word i, end (one past the last word), or nil.
	local function Match(w, i, slots, k, last)
		if k > #slots then
			if last and i <= #w then return nil end
			return i
		end
		local s, x = slots[k], w[i]
		if x and (s.alts[x] or (s.num and x:find("^%d+$")) or (s.unit and (x:find("^%d+yds?$") or x:find("^%d+yards?$")))) then
			local e = Match(w, i + 1, slots, k + 1, last)
			if e then return e end
		end
		if s.opt then return Match(w, i, slots, k + 1, last) end
		return nil
	end

	local function TrimSpaces(s) return (s:gsub("^ +", ""):gsub(" +$", "")) end

	-- Spaces and punctuation once words are gone from a clause.
	local function Tidy(s)
		return (s:gsub("  +", " "):gsub(" ([,%.;:!%?%)])", "%1"):gsub("%( ", "("):gsub("%(%)", ""):gsub('""', "")
			:gsub("  +", " "):gsub("^[ ,;:]+", ""):gsub("[ ,;:]+$", ""))
	end

	-- A clause without its claims: the same text when it makes none, "" when nothing else is in it.
	local function WithoutClaims(clause)
		local toks = Tokens(clause)
		local w = {}
		for k, t in ipairs(toks) do w[k] = t.w end
		local n = #w
		for k = 1, n do
			if COMPASS[w[k]] and not (w[k + 1] == "of" and SELF_WORDS[w[k + 2] or ""]) then return clause end
		end
		local marked, any = {}, false
		for _, r in ipairs(RULES) do
			for i = 1, r.first and math.min(1, n) or n do
				local e = Match(w, i, r.slots, 1, r.last)
				if e then
					local measured = false
					if r.near then
						for k = 1, n - 1 do
							if (k < i or k >= e) and MEASURED_FROM[w[k]] and not SELF_WORDS[w[k + 1]] then
								measured = true
								break
							end
						end
					end
					if not measured then
						any = true
						for k = i, e - 1 do marked[k] = true end
					end
				end
			end
		end
		if not any then return clause end
		for k = 2, n do
			if marked[k - 1] and not marked[k] and CLAIM_AFTER[w[k]] then marked[k] = true end
		end
		for k = n - 1, 1, -1 do
			if marked[k + 1] and not marked[k] and CLAIM_BEFORE[w[k]] then marked[k] = true end
		end
		if marked[n] then
			local k = n
			while k >= 1 and marked[k] do k = k - 1 end
			while k >= 1 and HANGING[w[k]] do
				marked[k] = true
				k = k - 1
			end
		end
		if marked[1] then
			local k = 1
			while k <= n and marked[k] do k = k + 1 end
			while k <= n and HANGING[w[k]] do
				marked[k] = true
				k = k + 1
			end
		end
		local content = false
		for k = 1, n do
			if not marked[k] and not NOT_CONTENT[w[k]] and not w[k]:find("^%d+$") then content = true end
		end
		if not content then return "" end
		-- Each run of claim words goes, from its first word's start to its last word's end.
		local parts, pos = {}, 1
		for k = 1, n do
			if marked[k] and not marked[k - 1] then
				local j = k
				while j < n and marked[j + 1] do j = j + 1 end
				parts[#parts + 1] = clause:sub(pos, toks[k].s - 1)
				pos = toks[j].e + 1
			end
		end
		parts[#parts + 1] = clause:sub(pos)
		return Tidy(table.concat(parts))
	end

	local function Clauses(body)
		local out, cs, i, sep = {}, 1, 1, ""
		while i <= #body do
			local hit
			for _, x in ipairs(SEPS) do
				if body:sub(i, i + #x - 1) == x then
					hit = x
					break
				end
			end
			if hit then
				out[#out + 1] = { sep = sep, text = body:sub(cs, i - 1) }
				sep, i = hit, i + #hit
				cs = i
			else
				i = i + 1
			end
		end
		out[#out + 1] = { sep = sep, text = body:sub(cs) }
		return out
	end

	function P.DropDistanceClaims(note)
		local s = tostring(note or "")
		if s == "" then return s end
		local changed = false
		-- A parenthesis, as one clause: without its claims, or gone when that's all it held.
		local t = s:gsub("( ?)%(([^()]*)%)", function(space, inner)
			local left = WithoutClaims(inner)
			if left == inner then return nil end
			changed = true
			if left == "" then return "" end
			return space .. "(" .. left .. ")"
		end)
		-- Sentences end at . ! or ? before a space, or at the end.
		local sentences, start = {}, 1
		while true do
			local p = t:find("[%.!%?] ", start)
			if not p then break end
			sentences[#sentences + 1] = t:sub(start, p)
			start = p + 2
		end
		if start <= #t then sentences[#sentences + 1] = t:sub(start) end
		local out = {}
		for _, sentence in ipairs(sentences) do
			local body, stop = sentence:match("^(.-)([%.!%?]*)$")
			local kept, edited = {}, false
			for _, c in ipairs(Clauses(body)) do
				local left = WithoutClaims(c.text)
				if left ~= c.text then edited = true end
				if left ~= "" then kept[#kept + 1] = { sep = c.sep, text = left } end
			end
			if not edited then
				out[#out + 1] = TrimSpaces(sentence)
			else
				changed = true
				local parts = {}
				for k, c in ipairs(kept) do parts[k] = (k > 1 and c.sep or "") .. c.text end
				local str = TrimSpaces(table.concat(parts))
				if str ~= "" then
					str = str:gsub("^[a-z]", string.upper)
					out[#out + 1] = str .. stop
				end
			end
		end
		if not changed then return s end
		return TrimSpaces(table.concat(out, " "))
	end
end

local function Truthy(v) return v ~= nil and v ~= false and v ~= 0 and v ~= "" end
local function Round2(v) return math.floor(v * 100 + 0.5) / 100 end
local function Finite(v) return type(v) == "number" and v == v and v ~= math.huge and v ~= -math.huge end

-- One command, cleaned, or nil (why in notes).
function P.MapCommand(c, notes)
	notes = notes or {}
	if type(c) ~= "table" or P.IsArray(c) then
		notes[#notes + 1] = "a map command isn't an object"
		return nil
	end
	if c.op == "clearall" then return { op = "clearall" } end
	local layer = (type(c.layer) == "string" or type(c.layer) == "number") and tostring(c.layer) or ""
	-- "__proto__" too, as the app refuses it (a name that's a hazard there).
	if #layer < 1 or #layer > MAP.layerName or not layer:match("^[%w_%.%-]+$") or layer == "__proto__" then
		notes[#notes + 1] = "a bad layer name"
		return nil
	end
	if c.op == "clear" then return { op = "clear", layer = layer } end
	if c.op ~= "set" then
		notes[#notes + 1] = "an unknown map command"
		return nil
	end
	if not P.IsArray(c.points) then
		notes[#notes + 1] = "a layer's points aren't a list"
		return nil
	end
	if type(c.title) == "table" then -- junk the app can't read either
		notes[#notes + 1] = "a layer's title isn't text"
		return nil
	end
	local points, noteChars = {}, 0
	for k = 1, math.min(#c.points, MAP.pointsPerLayer) do
		local p = c.points[k]
		local m = type(p) == "table" and tonumber(p.m)
		local x = type(p) == "table" and tonumber(p.x)
		local y = type(p) == "table" and tonumber(p.y)
		if m and m == math.floor(m) and m > 0 and m <= MAP.mapIdMax and Finite(x) and Finite(y) then
			local point = {
				m = m, x = Round2(math.min(100, math.max(0, x))), y = Round2(math.min(100, math.max(0, y))),
				label = CleanText(p.label, MAP.label), kind = KINDS[p.kind] and p.kind or "poi",
			}
			local note = P.DropDistanceClaims(CleanText(p.note, MAP.note))
			if note ~= "" and noteChars + #note <= MAP.layerNotes then
				point.note = note
				noteChars = noteChars + #note
			end
			if type(p.q) == "table" then
				local q, seen = {}, {}
				for _, v in ipairs(p.q) do
					local id = tonumber(v)
					if id and id == math.floor(id) and id > 0 and id < 1e6 and not seen[id] and #q < MAP.quests then
						seen[id] = true
						q[#q + 1] = id
					end
				end
				if #q > 0 then point.q = q end
			end
			points[#points + 1] = point
		end
	end
	if #points == 0 then
		notes[#notes + 1] = "a layer with no usable points"
		return nil
	end
	local title = CleanText((c.title ~= nil and c.title ~= "" and c.title ~= false) and c.title or layer, MAP.title)
	return { op = "set", layer = layer, title = title, ordered = Truthy(c.ordered), loop = Truthy(c.loop), points = points }
end

-- The map's layers now, in the form commands make, oldest first.
local function CurrentLayers()
	local list = {}
	local m = type(NQAMapDB) == "table" and NQAMapDB.map
	for _, l in ipairs(type(m) == "table" and type(m.layers) == "table" and m.layers or {}) do
		if type(l) == "table" and type(l.name) == "string" and type(l.points) == "table" then
			local points = {}
			for _, p in ipairs(l.points) do
				if type(p) == "table" then
					points[#points + 1] = { m = p[1], x = p[2], y = p[3], label = p[4], kind = p[5],
						note = (type(p[6]) == "string" and p[6] ~= "") and p[6] or nil, q = type(p[7]) == "table" and p[7] or nil }
				end
			end
			list[#list + 1] = { name = l.name, title = l.title, ordered = l.ordered, loop = l.loop, points = points }
		end
	end
	return list, m
end

-- Apply commands to the map. Returns the names of the layers they drew that
-- are on the map after them, in the order drawn (a reply's drew), and notes.
function P.ApplyMap(cmds, notes)
	notes = notes or {}
	local layers, cur = CurrentLayers()
	local changed, drew = false, {}
	local function find(name)
		for k, l in ipairs(layers) do
			if l.name == name then return k end
		end
	end
	for _, raw in ipairs(cmds or {}) do
		local c = P.MapCommand(raw, notes)
		if c and c.op == "clearall" then
			if #layers > 0 then layers, changed = {}, true end
		elseif c and c.op == "clear" then
			local k = find(c.layer)
			if k then
				table.remove(layers, k)
				changed = true
			end
		elseif c then
			local k = find(c.layer)
			if k then table.remove(layers, k) end
			layers[#layers + 1] = { name = c.layer, title = c.title, ordered = c.ordered, loop = c.loop, points = c.points }
			changed = true
			drew[#drew + 1] = c.layer
		end
	end
	-- Within the budget: the oldest layers go first, then the oldest layers' notes.
	local function total()
		local n = 0
		for _, l in ipairs(layers) do n = n + #l.points end
		return n
	end
	while #layers > MAP.layers or total() > MAP.totalPoints do
		table.remove(layers, 1)
		changed = true
	end
	local function noteChars()
		local n = 0
		for _, l in ipairs(layers) do
			for _, p in ipairs(l.points) do n = n + (p.note and #p.note or 0) end
		end
		return n
	end
	for _, l in ipairs(layers) do
		if noteChars() <= MAP.mapNotes then break end
		for _, p in ipairs(l.points) do p.note = nil end
	end
	if not changed then return {}, notes end
	local out = {}
	for _, l in ipairs(layers) do
		local points = {}
		for _, p in ipairs(l.points) do
			local row = { p.m, p.x, p.y, p.label or "", p.kind or "poi" }
			if p.note or p.q then row[6] = p.note or "" end
			if p.q then row[7] = p.q end
			points[#points + 1] = row
		end
		out[#out + 1] = { name = l.name, title = l.title, ordered = l.ordered and true or false, loop = l.loop and true or false, points = points }
	end
	local version = (type(cur) == "table" and cur.epoch == EPOCH and tonumber(cur.version) or 0) + 1
	if type(NQAMap) == "table" and type(NQAMap.Sync) == "function" then
		pcall(NQAMap.Sync, { epoch = EPOCH, version = version, layers = out })
	end
	-- Drawn and still there, once each, in order (the reply's drew; Chats.CleanDrew caps it).
	local on, list, seen = {}, {}, {}
	for _, l in ipairs(layers) do on[l.name] = true end
	for _, name in ipairs(drew) do
		if on[name] and not seen[name] then
			seen[name] = true
			list[#list + 1] = name
		end
	end
	return list, notes
end

---------------------------------------------------------------------------
-- A pasted reply, read: { text, summary, more, chips, refs, weights, map,
-- notes, empty, ours }. text and summary are ready to show (| doubled).
---------------------------------------------------------------------------

function P.Parse(raw)
	raw = ns.Utf8Cut(tostring(raw or ""), PASTE_MAX):gsub("\r\n?", "\n")
	local out = { notes = {}, map = {} }
	if not raw:match("%S") then
		out.empty = true
		return out
	end
	-- The message from step 1, whole or in part (its mark, or how its instructions start).
	if raw:find(P.MARK, 1, true) or raw:find(Instructions():sub(1, 40), 1, true) then
		out.ours = true
		return out
	end
	local text, found = TakeBlocks(raw)
	for _, b in ipairs(found) do
		if b.kind == "wowmap" then
			MapCommands(b.body, out.map, out.notes)
		elseif b.kind == "wowchips" then
			out.chips = Chips(Trim(b.body)) or out.chips
		elseif b.kind == "wowrefs" then
			out.refs = Refs(Trim(b.body)) or out.refs
		elseif b.kind == "wowweights" then
			out.weights = Weights(Trim(b.body)) or out.weights
		end
	end
	text = Trim(text:gsub("\n\n\n+", "\n\n"))
	local shown = P.Markdown(text)
	local summary = P.SplitSummary(text)
	if summary ~= "" then
		summary = Trim(InlinePlain((summary:gsub("%s*\n%s*", " "))))
	else
		summary = FirstSentence((shown:gsub("|c%x%x%x%x%x%x%x%x", ""):gsub("|r", ""):gsub("||", "|")))
	end
	out.summary = Pipes(Shorten(summary, SUMMARY_MAX))
	out.more = 0
	if #shown > TEXT_MAX then
		-- At a line break near the limit, never inside an escape or a character.
		-- [code health AD-02] The last line break, grey and close: anchored, so a text with
		-- none is one look, not one from every byte (12,000 squared, seconds in the game).
		local cut = TEXT_MAX
		local nl = shown:sub(1, TEXT_MAX):match("^.*()\n")
		if nl and nl > TEXT_MAX - 2000 then cut = nl - 1 end
		local head = ns.Utf8Cut(shown, cut)
		while head:sub(-1) == "|" do head = head:sub(1, -2) end
		out.more = #shown - #head
		if (head:match("^.*()" .. GRAY:gsub("|", "%%|")) or 0) > (head:match("^.*()|r") or 0) then head = head .. CLOSE end
		shown = head
	end
	out.text = shown
	out.empty = shown == "" and #out.map == 0 and not out.chips and not out.refs and not out.weights
	return out
end

---------------------------------------------------------------------------
-- The message for the AI: Bones's instructions, the game data, and what the
-- player wrote (shift-clicked links already expanded by Chats.Send). Nothing
-- names the character, the realm or the guild: an AI doesn't need them.
---------------------------------------------------------------------------

P.INSTRUCTIONS = [[You're NeverQuestAlone, a friendly guide for World of Warcraft: Forever (the original world on today's game client). A player is asking from inside the game, and they'll paste your reply back into a small window there. So:
- Put the useful part first. Keep it under about 1,200 characters and plain, with no tables or images.
- End with one line that starts with "TL;DR:" and sums up your reply in under 160 characters.
- Name only quests, items, spells, ids and places you're sure of. Map coordinates are the game's own: 0 to 100 across a map, as the minimap shows them.
- The quest chain lines are worked out for this character from classic quest data; trust them over what you remember. When you suggest quests, rank a step of a chain that leads to a dungeon, a raid or a rare or better reward higher, even if it looks minor, and say where it leads.

The game can also read extra blocks. Put each one in a code block with this exact language tag, before the TL;DR line:
- wowmap, to draw on their map, one line per layer, like:
{"op":"set","layer":"route","title":"Westfall quests","ordered":true,"points":[{"m":1436,"x":56.3,"y":47.5,"label":"1. Sentinel Hill","kind":"turnin","note":"Turn in Westfall Stew","q":[36]}]}
"m" is the map's id from the game data below. With "ordered":true the points are a numbered route the game leads them along, stop by stop. "kind" is one of quest, turnin, kill, loot, object, explore, npc, trainer, vendor, dungeon, flight, ore, herb, poi. "q" lists the quest ids for that stop. "note" says what to do at the stop, never how far or how close it is or that it's the nearest: the game shows the live distance. {"op":"clear","layer":"route"} takes a layer off.
- wowrefs, the ids you name, so they show as game links: {"q":[36],"i":[2140],"s":[8017]}
- wowweights, stat weights for their build, so the game rates gear for them: {"str":1.0,"sta":0.8,"agi":0.4}
- wowchips, up to 3 short questions they might ask next, one per line.
Only draw on the map when they ask for a route or a place, and say in your reply what you drew.]]

local function Field(o, k)
	if type(o) ~= "table" then return nil end
	if type(o._o) ~= "table" then return o[k] end
	for _, kv in ipairs(o._o) do
		if kv[1] == k then return kv[2] end
	end
end

-- Where gear is worn, by the game's inventory ids (INVSLOT_HEAD 1 to INVSLOT_TABARD 19).
local GEAR_PLACES = { "head", "neck", "shoulders", "shirt", "chest", "waist", "legs", "feet", "wrists", "hands",
	"finger 1", "finger 2", "trinket 1", "trinket 2", "back", "main hand", "off hand", "ranged", "tabard" }

local function Num(v)
	v = tonumber(v)
	if not v then return "?" end
	if v == math.floor(v) then return string.format("%d", v) end
	return string.format("%.1f", v)
end

-- The game data, as plain lines. The lines the app gets (Chats.GameContext),
-- the character's without its name, realm and guild; then the quest log, its
-- spots on this map and the gear, from the companion's reading of the game.
function P.GameData()
	local lines = {}
	local ctx = ns.Chats.GameContext and ns.Chats.GameContext() or ""
	local hasQuests = false
	for _, line in ipairs(Lines(ctx)) do
		if line:find("^Character: ") then
			local level, race, class = ns.Try(UnitLevel, "player"), ns.Try(UnitRace, "player"), ns.Try(UnitClass, "player")
			local faction = ns.Try(UnitFactionGroup, "player")
			local desc = {}
			if level then desc[#desc + 1] = "level " .. tostring(level) end
			if race then desc[#desc + 1] = tostring(race) end
			if class then desc[#desc + 1] = tostring(class) end
			line = #desc > 0 and ("Character: " .. table.concat(desc, " ") .. (faction and (" (" .. tostring(faction) .. ")") or "")) or nil
		elseif line:find("^Quest log") then
			line = nil
		end
		if line and line:match("%S") then lines[#lines + 1] = line end
	end
	local g = ns.Companion and ns.Companion.Call("Gather") or nil
	local quests = type(g) == "table" and g.quests or nil
	if type(quests) == "table" and #quests > 0 then
		lines[#lines + 1] = "Quest log (id, level, title, then objectives as have/need; * means ready to turn in):"
		for _, q in ipairs(quests) do
			local objs = {}
			for _, o in ipairs(type(q.obj) == "table" and q.obj or {}) do
				objs[#objs + 1] = string.format("%s %s/%s", tostring(o.text or ""), Num(o.have), Num(o.need))
			end
			lines[#lines + 1] = string.format("%s%s L%s %s%s", Num(q.id), q.complete and "*" or "", Num(q.level), tostring(q.title or ""),
				#objs > 0 and (": " .. table.concat(objs, ", ")) or "")
		end
		hasQuests = true
	end
	-- Where quest chains lead (Chains.lua): the log's, and those the character can start near their level.
	if ns.Chains then
		local chained = {}
		for _, q in ipairs(type(quests) == "table" and quests or {}) do
			if type(q.chain) == "table" then chained[#chained + 1] = string.format("%s: %s", Num(q.id), ns.Chains.Words(q.chain)) end
		end
		if #chained > 0 then
			lines[#lines + 1] = string.format("Quest chains in the log (quest id: step, where the chain leads, the next quest): %s", table.concat(chained, "; "))
		end
		local starts = {}
		for _, st in ipairs(type(g) == "table" and g.chainStarts or {}) do
			local facts = { step = 1 }
			for _, kv in ipairs(type(st) == "table" and st._o or {}) do facts[kv[1]] = kv[2] end
			-- Named for each place: 1 quest id, 2 its title (when the game has it), 3 level, 4 the zone (when
			-- the game names it), 5 the chain in words.
			starts[#starts + 1] = string.format("%s%s, level %s%s: %s", Num(facts.id), facts.title and (" " .. tostring(facts.title)) or "",
				Num(facts.level), facts.zone and (", " .. tostring(facts.zone)) or "", ns.Chains.Words(facts))
		end
		if #starts > 0 then
			lines[#lines + 1] = string.format("Quest chains they can start near their level (quest id, title, level, zone: step, where the chain leads, the next quest): %s", table.concat(starts, "; "))
		end
	end
	local poi = type(g) == "table" and g.poi or nil
	if type(poi) == "table" and #poi > 0 then
		local spots = {}
		for _, p in ipairs(poi) do
			spots[#spots + 1] = string.format("%s at %s, %s on map %s", Num(Field(p, "id")), Num(Field(p, "x")), Num(Field(p, "y")), Num(Field(p, "map")))
		end
		lines[#lines + 1] = string.format("Where the game shows quest objectives (quest id at x, y): %s", table.concat(spots, "; "))
	end
	local gear = type(g) == "table" and g.gear or nil
	if type(gear) == "table" and #gear > 0 then
		local items = {}
		for _, it in ipairs(gear) do
			local where = GEAR_PLACES[tonumber(Field(it, "slot")) or 0] or Num(Field(it, "slot"))
			-- Named for each place: 1 where, 2 item id, 3 item level.
			items[#items + 1] = string.format("%s: item %s (item level %s)", where, Num(Field(it, "id")), Num(Field(it, "ilvl")))
		end
		lines[#lines + 1] = string.format("Gear worn: %s", table.concat(items, "; "))
	end
	if not hasQuests then
		-- Without the companion's reading, the quest ids the app gets.
		for _, line in ipairs(Lines(ctx)) do
			if line:find("^Quest log") then lines[#lines + 1] = line end
		end
	end
	return table.concat(lines, "\n")
end

-- The message to copy: the mark, the instructions, the game data, the words.
function P.Compose(entry)
	local parts = { P.MARK, Instructions() }
	local data = (entry and not entry.bare and ns.db.settings.context) and P.GameData() or ""
	if data ~= "" then
		parts[#parts + 1] = string.format("Game data, read from the game just now:\n%s", data)
	else
		parts[#parts + 1] = "No game data came with this message."
	end
	parts[#parts + 1] = string.format("The player's message:\n%s", tostring(entry and entry.text or ""))
	return table.concat(parts, "\n\n")
end

---------------------------------------------------------------------------
-- Sending, receiving and stopping
---------------------------------------------------------------------------

-- Where the NeverQuestAlone app is downloaded: the releases page, the one place that has the
-- Mac and Windows downloads the moment a release publishes, and the page the app itself sends
-- players to (UX-W01). The addon can't open a browser: /bones app shows it to copy.
P.APP_PAGE = "https://github.com/tommygeoco/neverquestalone/releases"

-- The first line of an empty chat while messages go by Copy and Paste.
P.STARTER = "Ask anything. Each message opens a window where you copy it into ChatGPT, Claude or another AI and paste its reply back."

-- [C-137] The HUD's first-run Welcome while messages go by Copy and Paste and no app has answered
-- (main 0.5.4's words): Ask works now, so the app-only setup rows stay out of the way.
P.WELCOME = "I'm NeverQuestAlone. Click Ask and ask me anything: each message opens a window where you copy it into ChatGPT, Claude or another AI and paste its reply back. Ctrl+right-click the world map to ask about a spot, or right-click a quest in your log. The free NeverQuestAlone app skips the copying: type /nqa app for the link. Click my portrait for all our chats."

-- [C-133] The window's first line when Automatic falls back to Copy and Paste.
P.FALLBACK = "The NeverQuestAlone app hasn't answered for a while, so this message goes by Copy and Paste. Once it's back, replies come by themselves again."

-- Transport.Heard, the first time an app answers this install: once, where the player looks.
function P.OnLinked()
	local waiting = P.Newest()
	local text = waiting
		and "The NeverQuestAlone app is running, so replies come back by themselves now. The message already waiting still takes a pasted reply."
		or "The NeverQuestAlone app is running, so replies come back by themselves now."
	ns.Notify.Local(text)
	local chat = ns.Chats.Active()
	if chat then ns.Chats.Notice(chat, text) end
	if ns.HUD and ns.HUD.Active() then
		ns.HUD.Flash("The app is running", waiting and "Your waiting message still takes a pasted reply." or "Replies come back by themselves now.", text, "warn")
	end
end

-- Copy and Paste is the way for new messages: picked in Settings, or no
-- NeverQuestAlone app has answered this install yet.
function P.On()
	local db = ns.db
	if not db or type(db.settings) ~= "table" then return false end
	if db.settings.replies == "paste" or not db.linked then return true end
	-- Automatic, with the app gone quiet (no word for two minutes): an ask
	-- never waits on an app that isn't there.
	-- [UX-1] The light is red for the AI's own states too (a rejected key,
	-- no credit left) while the app answers, and the app says what to do about
	-- those: only its silence counts.
	return ns.Transport.Light() == "red" and not ns.Transport.BridgeAlive()
end

-- A message of the chat's waiting for a pasted reply: the one with this key,
-- else the newest (what the player asked last), or nil.
function P.Waiting(chat, key)
	local list = type(chat) == "table" and chat.pending or {}
	for i = #list, 1, -1 do
		local p = list[i]
		if p.paste and (key == nil or p.key == key) then return p end
	end
end

-- The newest message waiting for a pasted reply in any chat (Quick questions
-- included, where the HUD's asks go): chat, entry; or nil.
function P.Newest()
	local best, bestChat
	for _, chat in ipairs(ns.db and ns.db.chats or {}) do
		local p = P.Waiting(chat)
		if p and (not best or (p.t or 0) >= (best.t or 0)) then best, bestChat = p, chat end
	end
	return bestChat, best
end

-- The history entry a waiting message came from.
local function EntryOf(chat, p)
	for i = #chat.history, 1, -1 do
		local e = chat.history[i]
		if e.role == "user" and e.key == p.key then return e end
	end
end

local ui = {} -- the Copy and Paste window's parts (below)
local counter = 0
local afterFight -- { chat, key }: a message asked in combat, whose window opens when it ends
-- Chats.Send, once the text is checked: the message waits here for its reply.
-- It isn't the app's (chat.sent stays as it was: a rename or a delete of this
-- chat has nothing to tell an app), and one message waits per chat: a newer
-- one replaces it. In combat the window waits for the fight to end, so no
-- key meant for an ability lands in it.
function P.Send(chat, text, raw, skip, wasBusy)
	counter = counter + 1
	local key = string.format("paste_%d_%d", time(), counter)
	for i = #chat.pending, 1, -1 do
		if chat.pending[i].paste then
			table.remove(chat.pending, i)
			ns.Chats.AddHistory(chat, { role = "system", text = "Replaced by your newer message.", kind = "aborted" })
		end
	end
	table.insert(chat.pending, { key = key, t = time(), paste = true, acked = true })
	ns.Chats.AddHistory(chat, { role = "user", text = text, typed = raw ~= text and raw or nil, key = key, bare = skip or nil })
	if InCombatLockdown() then
		afterFight = { chat = chat.id, key = key }
		ns.Notify.Game(P.Named("Asked NeverQuestAlone: your message opens after the fight."))
	else
		P.Open(chat.id, key)
	end
	ns.Refresh()
	return key
end

-- The fight is over: the message asked during it opens, if it still waits.
ns.On("PLAYER_REGEN_ENABLED", function()
	local a = afterFight
	afterFight = nil
	if a then P.Open(a.chat, a.key) end
end)

-- A fight starts with the window open: the keys go back to the game.
ns.On("PLAYER_REGEN_DISABLED", function()
	if ui.outBox then ui.outBox:ClearFocus() end
	if ui.inBox then ui.inBox:ClearFocus() end
end)

-- At login, a message left waiting for an hour or more (a closed game, a
-- reply never pasted) stops waiting, so the HUD and the chat move on.
local STALE = 3600
ns.On("PLAYER_LOGIN", function()
	local ended = false
	for _, chat in ipairs(ns.db and ns.db.chats or {}) do
		for i = #chat.pending, 1, -1 do
			local p = chat.pending[i]
			if p.paste and time() - (tonumber(p.t) or 0) >= STALE then
				table.remove(chat.pending, i)
				ns.Chats.AddHistory(chat, { role = "system", text = "No reply was pasted, so this stopped waiting. Ask again any time.", kind = "aborted" })
				ended = true
			end
		end
	end
	if ended then ns.Refresh() end
end)

-- A pasted reply for the chat's waiting message. Returns true, or false and
-- why ("key": it's shaped like an API key; "ours": the message itself was
-- pasted; "empty"; "none": nothing waits).
function P.Receive(chatId, raw, key)
	-- [code health AD-01] (KY-10) A key pasted here is refused as one typed in the
	-- window is, before anything keeps it: no history, nothing in saved data.
	if ns.Chats.KeyShaped(raw) then return false, "key" end
	local chat = ns.Chats.Find(chatId)
	local p = chat and P.Waiting(chat, key)
	if not p then return false, "none" end
	local r = P.Parse(raw)
	if r.ours then return false, "ours" end
	if r.empty then return false, "empty" end
	local drew = P.ApplyMap(r.map, r.notes)
	local rec = {
		t = "reply", chat = chat.id, mid = "paste:" .. p.key, agent = chat.agent, text = r.text, summary = r.summary, more = r.more,
		chips = r.chips, refs = r.refs, weights = r.weights, drew = #drew > 0 and drew or nil, pasteKey = p.key,
	}
	local note = ns.Chats.ApplyRecord(chat, rec, false)
	if note then ns.Notify.Push({ note }) end
	if P.ShownFor() == chat.id then P.Close() end
	ns.Refresh()
	return true
end

-- Stop waiting for a message of the chat's (this key's, else the newest
-- waiting; Stop, /bones stop): nothing was sent anywhere.
function P.Stop(chat, key)
	for i = #chat.pending, 1, -1 do
		local p = chat.pending[i]
		if p.paste and (key == nil or p.key == key) then
			table.remove(chat.pending, i)
			ns.Chats.AddHistory(chat, { role = "system", text = "Stopped. That message won't get a reply.", kind = "aborted" })
			if P.ShownFor() == chat.id then P.Close() end
			ns.Refresh()
			return true
		end
	end
	return false
end

---------------------------------------------------------------------------
-- The Copy and Paste window: the message to copy, selected, and a box for
-- the reply, read the moment it's pasted. Built on first use.
---------------------------------------------------------------------------

local W, H, PAD, BOX_H = 600, 470, 16, 116

local function Key(letter)
	return ((type(IsMacClient) == "function" and IsMacClient()) and "Cmd+" or "Ctrl+") .. letter
end

-- A dark, bordered, scrolling box with a multi-line EditBox in it.
local function Box(parent, name)
	local holder = ns.UI.Create("Frame", nil, parent, { "BackdropTemplate" })
	holder:SetSize(W - 2 * PAD, BOX_H)
	if holder.SetBackdrop then
		holder:SetBackdrop({ bgFile = "Interface\\ChatFrame\\ChatFrameBackground", edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border",
			tile = true, tileSize = 16, edgeSize = 12, insets = { left = 3, right = 3, top = 3, bottom = 3 } })
		holder:SetBackdropColor(0, 0, 0, 0.6)
	end
	local sc = ns.UI.Create("ScrollFrame", name .. "Scroll", holder, { "UIPanelScrollFrameTemplate" })
	sc:SetPoint("TOPLEFT", holder, "TOPLEFT", 8, -8)
	sc:SetPoint("BOTTOMRIGHT", holder, "BOTTOMRIGHT", -28, 8)
	local eb = CreateFrame("EditBox", name, sc)
	eb:SetMultiLine(true)
	eb:SetAutoFocus(false)
	eb:SetFontObject(ChatFontNormal)
	eb:SetMaxLetters(0)
	eb:SetSize(W - 2 * PAD - 40, BOX_H - 16)
	eb:SetScript("OnEscapePressed", function() P.Close() end)
	eb:SetScript("OnEditFocusLost", function(self) self:HighlightText(0, 0) end)
	sc:SetScrollChild(eb)
	if sc.HookScript then sc:HookScript("OnSizeChanged", function(_, w) if w then eb:SetWidth(w) end end) end
	-- A click anywhere in the box puts the cursor in it.
	holder:EnableMouse(true)
	holder:SetScript("OnMouseDown", function() eb:SetFocus() end)
	return holder, eb
end

-- What a paste or a keystroke put into text that was old: the part that
-- isn't the old text's start or end. When most of the old text is gone, it
-- was selected and replaced, so all of the new text is what came in (a reply
-- that happens to end as the message does keeps its ending).
local function Inserted(old, new)
	local a = 0
	while a < #old and a < #new and old:byte(a + 1) == new:byte(a + 1) do a = a + 1 end
	local b = 0
	while b < #old - a and b < #new - a and old:byte(#old - b) == new:byte(#new - b) do b = b + 1 end
	if a + b < #old / 2 then return new end
	return new:sub(a + 1, #new - b)
end

local function Say(text, error)
	if not ui.status then return end
	ui.status:SetText(text or "")
	if error then ui.status:SetTextColor(1, 0.44, 0.44) else ui.status:SetTextColor(0.8, 0.8, 0.8) end
end

local function Build()
	if ui.frame then return ui.frame end
	local f, tpl = ns.UI.Create("Frame", "NQAPaste", UIParent, { "BasicFrameTemplateWithInset", "BackdropTemplate" })
	if tpl ~= "BasicFrameTemplateWithInset" and f.SetBackdrop then
		f:SetBackdrop({ bgFile = "Interface\\DialogFrame\\UI-DialogBox-Background", edgeFile = "Interface\\DialogFrame\\UI-DialogBox-Border",
			tile = true, tileSize = 32, edgeSize = 32, insets = { left = 11, right = 12, top = 12, bottom = 11 } })
	end
	f:SetSize(W, H)
	f:SetPoint("CENTER", UIParent, "CENTER", 0, 40)
	f:SetFrameStrata("DIALOG")
	f:SetMovable(true)
	f:SetClampedToScreen(true)
	f:EnableMouse(true)
	f:RegisterForDrag("LeftButton")
	f:SetScript("OnDragStart", f.StartMoving)
	f:SetScript("OnDragStop", f.StopMovingOrSizing)
	f:Hide()
	tinsert(UISpecialFrames, "NQAPaste") -- Esc closes it; the message keeps waiting
	local title = ns.UI.Child(f, "TitleText") or f:CreateFontString(nil, "OVERLAY", "GameFontNormal")
	if not ns.UI.Child(f, "TitleText") then title:SetPoint("TOP", f, "TOP", 0, -14) end
	title:SetText("Copy and Paste")
	if not ns.UI.Child(f, "CloseButton") then
		local x = ns.UI.Create("Button", nil, f, { "UIPanelCloseButton" })
		x:SetPoint("TOPRIGHT", f, "TOPRIGHT", -4, -4)
		x:SetScript("OnClick", function() P.Close() end)
	end

	local y = -34
	ui.step1 = f:CreateFontString(nil, "OVERLAY", "GameFontNormal")
	ui.step1:SetPoint("TOPLEFT", f, "TOPLEFT", PAD, y)
	ui.step1:SetText("1 Copy Your Message")
	ui.hint1 = f:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
	ui.hint1:SetPoint("TOPLEFT", ui.step1, "BOTTOMLEFT", 0, -4)
	ui.hint1:SetWidth(W - 2 * PAD)
	ui.hint1:SetJustifyH("LEFT")
	-- One read of the reply box, 0.3 s after the last change: each change re-arms it.
	local function ReadSoon()
		ui.readTok = (ui.readTok or 0) + 1
		local t = ui.readTok
		C_Timer.After(0.3, function() if t == ui.readTok then P.UseBox(true) end end)
	end
	ui.out, ui.outBox = Box(f, "NQAPasteOut")
	-- A click or the focus selects all of the message again, so the copy key copies all of it.
	ui.outBox:SetScript("OnEditFocusGained", function(self) self:HighlightText() end)
	ui.outBox:SetScript("OnMouseUp", function(self) self:HighlightText() end)
	ui.out:SetPoint("TOPLEFT", ui.hint1, "BOTTOMLEFT", 0, -6)
	-- The message is for copying: typing puts it back, a paste here is the
	-- reply in the wrong box (it goes to step 2 and is read), and the copy
	-- key moves on to the reply box, ready for the paste when you come back.
	ui.outBox:SetScript("OnTextChanged", function(self, userInput)
		local now = self:GetText() or ""
		if not userInput or not ui.message or now == ui.message then return end
		local pasted = Inserted(ui.message, now)
		self:SetText(ui.message)
		self:HighlightText()
		if #pasted >= AUTO_APPLY then
			ui.inBox:SetText(pasted)
			ui.lastLen, ui.lastText = #pasted, pasted
			ui.inBox:SetFocus()
			ReadSoon()
		else
			-- [C-135] A key typed here is put back, and the player is told why.
			Say("This box holds your message to copy. Press Esc to play; Paste Reply in the HUD brings it back.")
		end
	end)
	ui.outBox:SetScript("OnKeyDown", function(_, key)
		local chord = (type(IsControlKeyDown) == "function" and IsControlKeyDown()) or (type(IsMetaKeyDown) == "function" and IsMetaKeyDown())
		if key == "C" and chord then
			ui.copied = true
			C_Timer.After(0.1, function()
				if ui.frame and ui.frame:IsShown() then
					ui.inBox:SetFocus()
					Say("Copied. Paste it into your AI, then paste your AI's reply under step 2.")
				end
			end)
		end
	end)

	ui.step2 = f:CreateFontString(nil, "OVERLAY", "GameFontNormal")
	ui.step2:SetPoint("TOPLEFT", ui.out, "BOTTOMLEFT", 0, -14)
	ui.step2:SetText("2 Paste Your AI's Reply")
	ui.hint2 = f:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
	ui.hint2:SetPoint("TOPLEFT", ui.step2, "BOTTOMLEFT", 0, -4)
	ui.hint2:SetWidth(W - 2 * PAD)
	ui.hint2:SetJustifyH("LEFT")
	ui.inn, ui.inBox = Box(f, "NQAPasteIn")
	ui.inn:SetPoint("TOPLEFT", ui.hint2, "BOTTOMLEFT", 0, -6)
	ui.inBox:SetMaxLetters(PASTE_MAX)
	-- A paste is read by itself, with no click, once the box has been still
	-- for a moment: a client that feeds a paste in one character at a time
	-- re-arms the one read with each, so the whole reply is read once. A key
	-- typed here (a W meant for walking) is read too: it has no TL;DR line and
	-- is short, so the read empties the box and says what the box is for.
	ui.inBox:SetScript("OnTextChanged", function(self, userInput)
		local text = self:GetText() or ""
		local grew = #text - (ui.lastLen or 0)
		ui.lastLen, ui.lastText = #text, text
		if userInput and grew >= 1 then ReadSoon() end
	end)

	ui.status = f:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
	ui.status:SetPoint("TOPLEFT", ui.inn, "BOTTOMLEFT", 0, -10)
	ui.status:SetWidth(W - 2 * PAD - 220)
	ui.status:SetJustifyH("LEFT")
	ui.close = ns.UI.Button(f, "Close", 90, function() P.Close() end)
	ui.close:SetPoint("BOTTOMRIGHT", f, "BOTTOMRIGHT", -PAD, 14)
	-- Stop: no reply is coming for this message (Close keeps it waiting).
	ui.stop = ns.UI.Button(f, "Stop", 80, function()
		local chat = ui.chat and ns.Chats.Find(ui.chat)
		if chat then P.Stop(chat, ui.key) end
	end)
	ui.stop:SetPoint("BOTTOMLEFT", f, "BOTTOMLEFT", PAD, 14)
	ui.use = ns.UI.Button(f, "Use Reply", 110, function() P.UseBox(false) end)
	ui.use:SetPoint("RIGHT", ui.close, "LEFT", -8, 0)
	-- What each does to the waiting message: Close keeps it, Stop drops it.
	for b, tip in pairs({
		[ui.close] = { title = "Close", key = "Esc", text = "Closes this window. Your message keeps waiting for its reply.", note = "Paste Reply in the HUD or /nqa paste brings it back." },
		[ui.stop] = { title = "Stop", text = "Drops this message: it won't get a reply." },
		[ui.use] = { title = "Use Reply", text = "Reads the reply under step 2. A paste is read by itself." },
	}) do
		b:SetScript("OnEnter", function(self) ns.Tip(self, tip, "ANCHOR_TOP") end)
		b:SetScript("OnLeave", function() if GameTooltip then GameTooltip:Hide() end end)
	end
	ui.frame = f
	return f
end

-- Which chat the window is open for, or nil.
function P.ShownFor()
	return ui.frame and ui.frame:IsShown() and ui.chat or nil
end

function P.Close()
	if ui.frame then ui.frame:Hide() end
end

-- Open the window for a chat's waiting message (that chat's newest, or with
-- no chat the newest in any chat). The first time, the message is selected
-- to copy; after that (Paste Reply, /bones paste), the cursor waits in step 2
-- for the reply. Returns false when no message waits.
function P.Open(chatId, key)
	local chat, p
	if chatId then
		chat = ns.Chats.Find(chatId)
		p = chat and P.Waiting(chat, key)
	else
		chat, p = P.Newest()
	end
	local entry = p and EntryOf(chat, p)
	if not entry then return false end
	Build()
	local again = p.opened
	p.opened = true
	local sameKey = ui.key == p.key
	ui.chat, ui.key = chat.id, p.key
	ui.message = P.Compose(entry)
	ui.copied = nil
	ui.hint1:SetText(string.format(P.Named(entry.bare
		and "Your message is selected, with how NeverQuestAlone should answer. Press %s, then paste it into ChatGPT, Claude or another AI."
		or "Your message is selected, with your game data and how NeverQuestAlone should answer. Press %s, then paste it into ChatGPT, Claude or another AI."), Key("C")))
	ui.hint2:SetText(string.format("Copy your AI's whole reply (most AIs have a Copy button under it), come back, click the box below and press %s.", Key("V")))
	ui.outBox:SetText(ui.message)
	if not again or not sameKey then
		ui.inBox:SetText("")
		ui.lastLen, ui.lastText = 0, ""
	end
	ui.frame:Show()
	if again then
		Say(string.format("Press %s to paste your AI's reply under step 2.", Key("V")))
		ui.inBox:SetFocus()
	else
		-- [C-133] Automatic fell back to Copy and Paste: say why, not the first-run words.
		local db = ns.db
		local fellBack = db and db.linked and type(db.settings) == "table" and db.settings.replies ~= "paste"
		Say(fellBack and P.FALLBACK or "Your AI's reply shows in the chat as soon as you paste it.")
		ui.outBox:SetFocus()
		ui.outBox:HighlightText()
	end
	return true
end

-- Read the reply box (a paste just arrived, or Use Reply).
function P.UseBox(auto)
	if not ui.frame or not ui.frame:IsShown() or not ui.chat then return false end
	local text = ui.inBox:GetText() or ""
	-- Read by itself only what looks like a reply (the TL;DR line the
	-- instructions ask for, or a block for the map): a link or a stray
	-- paste doesn't end the wait. A key goes on to be refused (AD-01).
	if auto and text:match("%S") and not (text:find("[Tt][Ll];?%s*[Dd][Rr]") or text:find("```wow", 1, true)) and not P.Parse(text).ours
		and not ns.Chats.KeyShaped(text) then
		-- [C-140, UX-W15] A few stray keys (a W meant for walking) are not a
		-- reply and not worth a click: the box is emptied and says what it is for,
		-- so the next paste is read clean. A paste fed one character at a time
		-- arrives whole before this read, and a link keeps the line below.
		if #text < 40 and not text:find("\n", 1, true) and not text:find("://", 1, true) and not text:find("www.", 1, true) then
			ui.inBox:SetText("")
			ui.lastLen, ui.lastText = 0, ""
			Say("This box takes your AI's reply: paste it here. Press Esc to play.")
			return false
		end
		Say("That doesn't look like your AI's reply: it has no TL;DR line. Click Use Reply to use it anyway.", true)
		return false
	end
	local ok, why = P.Receive(ui.chat, text, ui.key)
	if ok then
		ui.inBox:SetText("")
		ui.lastLen, ui.lastText = 0, ""
		return true
	end
	if why == "key" then
		-- [code health AD-01] (KY-10) Out of the box at once, with the refusal's own words.
		ui.inBox:SetText("")
		ui.lastLen, ui.lastText = 0, ""
		Say(ns.Chats.KeyRefused(), true)
	elseif why == "ours" then
		Say("That's your message from step 1. Copy your AI's reply and paste it here.", true)
	elseif why == "none" then
		P.Close()
		ns.Notify.Local("That message isn't waiting for a reply anymore.")
	elseif not auto then
		Say("Paste your AI's reply here first.", true)
	end
	return false
end
