// The Lua block Paste.lua carries (code health AD-13): Copy and Paste holds a pasted reply to the
// app's own limits (bridge/app/render.mjs) and map limits (bridge/app/map-protocol.mjs MAP_LIMITS,
// MAP_KINDS), and takes distance claims out of a stop's note by the app's own list and words
// (map-protocol.mjs DISTANCE_CLAIMS and the sets beside it). Made here from the bridge's exports, so
// the two can't drift; tests/paste_test.mjs checks that Paste.lua carries it byte for byte. Regenerate with:
//   node -e "import('./tests/helpers/paste-lua.mjs').then(m => process.stdout.write(m.pasteLuaSource()))"
// and paste it over the block (its first line to its last).
// FIRST_LINE still names bridge/protocol.js, where these exports lived until code health BR-24 moved
// them to map-protocol.mjs unchanged: the block Paste.lua carries stays byte for byte what it was.
import { RECORD_TEXT_MAX, SUMMARY_MAX, CHIPS_MAX, CHIP_CHARS, REFS_MAX } from '../../bridge/app/render.mjs';
import * as P from '../../bridge/app/map-protocol.mjs';

export const FIRST_LINE = '-- AD-13: generated by tests/helpers/paste-lua.mjs from bridge/app/render.mjs and bridge/protocol.js; do not edit by hand.';
export const LAST_LINE = '-- AD-13: the end of the generated block.';

// A Lua string literal: printable ASCII as it is, anything else as \ddd bytes.
function lua(s) {
  let out = '"';
  for (const b of Buffer.from(String(s), 'utf8')) {
    if (b === 0x22 || b === 0x5c) out += '\\' + String.fromCharCode(b);
    else if (b < 0x20 || b >= 0x7f) out += '\\' + b;
    else out += String.fromCharCode(b);
  }
  return out + '"';
}
const list = words => `{ ${[...words].map(lua).join(', ')} }`;
// A long list under its key, as many entries a line as fit in about 110 characters.
function rows(words) {
  const out = [];
  let line = '';
  for (const w of [...words].map(lua)) {
    if (line && line.length + w.length + 2 > 110) { out.push(`\t\t${line},`); line = ''; }
    line = line ? `${line}, ${w}` : w;
  }
  if (line) out.push(`\t\t${line},`);
  return out.join('\n');
}

export function pasteLuaSource() {
  const M = P.MAP_LIMITS;
  const map = ['layers', 'pointsPerLayer', 'totalPoints', 'label', 'title', 'note', 'quests', 'layerNotes', 'mapNotes', 'layerName', 'mapIdMax']
    .map(k => { if (!Number.isInteger(M[k])) throw new Error(`MAP_LIMITS.${k}`); return `${k} = ${M[k]}`; });
  return [
    FIRST_LINE,
    `local TEXT_MAX = ${RECORD_TEXT_MAX} -- bytes of a reply's text (RECORD_TEXT_MAX)`,
    `local SUMMARY_MAX = ${SUMMARY_MAX} -- characters of the TL;DR (SUMMARY_MAX)`,
    `local CHIPS_MAX, CHIP_CHARS, REFS_MAX = ${CHIPS_MAX}, ${CHIP_CHARS}, ${REFS_MAX}`,
    '-- A pasted route is held to what a route from the app is (MAP_LIMITS, MAP_KINDS).',
    `local MAP = { ${map.join(', ')} }`,
    `local KINDS = { ${[...P.MAP_KINDS].map(k => `${k} = true`).join(', ')} }`,
    '-- The distance claims a stop\'s note loses, and the words around them (DISTANCE_CLAIMS and its sets).',
    'local CLAIMS = {',
    '\tDISTANCE_CLAIMS = {',
    rows(P.DISTANCE_CLAIMS),
    '\t},',
    `\tMEASURED_FROM = ${list(P.MEASURED_FROM)},`,
    `\tSELF_WORDS = ${list(P.SELF_WORDS)},`,
    `\tCOMPASS = ${list(P.COMPASS)},`,
    `\tCLAIM_AFTER = ${list(P.CLAIM_AFTER)},`,
    `\tCLAIM_BEFORE = ${list(P.CLAIM_BEFORE)},`,
    '\tHANGING = {',
    rows(P.HANGING),
    '\t},',
    '\tNOT_CONTENT = {',
    rows(P.NOT_CONTENT),
    '\t},',
    `\tCLAUSE_SEPS = ${list(P.CLAUSE_SEPS)},`,
    '}',
    LAST_LINE,
    '',
  ].join('\n');
}
