#!/bin/bash
# Builds "NeverQuestAlone Capture.app" (PRD §9.10): swift build, wrap the binary in a
# minimal LSUIElement bundle, sign it with the stable local identity.
#
# The stable identity matters: Screen Recording is granted to the app's code
# signature. A self-signed certificate keeps the same designated requirement
# across rebuilds; ad hoc signing would tie the grant to each build's hash and
# every rebuild would silently lose it. So without the identity this script
# refuses to build an app unless --adhoc is given (for local experiments only;
# never grant Screen Recording to an ad hoc build).
#
#   bridge/capture/mac/build-app.sh [--adhoc] [--public] [--universal]
#   NQA_SIGN_IDENTITY="Other Name" bridge/capture/mac/build-app.sh
#
# --public builds NeverQuestAlone's helper (what app/desktop/scripts/dist.mjs
# packs): its own bundle id, from app/desktop/build/bridge/capture/mac/BUNDLE_ID
# (the file the packaged app carries as bridge/capture/mac/BUNDLE_ID), into
# build-public/, with its own Swift build folder. So it never shares a Screen
# Recording entry with your build, and uninstalling NeverQuestAlone never
# resets yours (final review L3-4).
#
# --universal builds the binary for arm64 and x86_64 in one SwiftPM run, in its
# own build folder, so the helper runs on every Mac (systems critic SY-16):
# @electron/universal takes a helper that is already universal as it is, and the
# universal DMG and both per-architecture update zips carry one that runs
# (release.yml checks each app's helper with lipo). One script and one build of
# each slice (SY-09: a second script used to build this Mac's slice first).
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
IDENTITY="${NQA_SIGN_IDENTITY:-NeverQuestAlone Local Code Signing}"
ADHOC=0
PUBLIC=0
UNIVERSAL=0
for arg in "$@"; do
  case "$arg" in
    --adhoc) ADHOC=1 ;;
    --public) PUBLIC=1 ;;
    --universal) UNIVERSAL=1 ;;
    *) echo "unknown argument: $arg (build-app.sh [--adhoc] [--public] [--universal])" >&2; exit 2 ;;
  esac
done

# Each build's bundle id has one source: BUNDLE_ID (yours), or the packaged
# app's (--public). Info.plist, main.swift (through the generated BundleID.swift)
# and the bridge's code requirement (transport/capture.mjs) read it.
readid() {
  local id
  id="$(tr -d '[:space:]' < "$1")"
  if ! [[ "$id" =~ ^[A-Za-z0-9][A-Za-z0-9.-]*$ ]]; then
    echo "bad bundle id in $1: '$id'" >&2
    exit 2
  fi
  printf '%s' "$id"
}
PRIVATE_ID="$(readid "$HERE/BUNDLE_ID")"
PUBLIC_ID="$(readid "$HERE/../../../app/desktop/build/bridge/capture/mac/BUNDLE_ID")"
if [ "$PUBLIC" -eq 1 ]; then
  BUNDLE_ID="$PUBLIC_ID"
  OUT="$HERE/build-public"
  SWIFT_ARGS=(--scratch-path "$HERE/.build-public" -Xswiftc -DNQA_PUBLIC_ID)
  # The name System Settings shows in Screen & System Audio Recording, and why it asks (onboarding
  # spec §9.4; the file keeps its name until B5.2 checks which one the pane lists, plan C9).
  NAME="NeverQuestAlone"
  USAGE="NeverQuestAlone reads only the top of the World of Warcraft window, where its addon draws, and nothing else. It keeps no pictures."
  COPYRIGHT="MIT. NeverQuestAlone."
else
  BUNDLE_ID="$PRIVATE_ID"
  OUT="$HERE/build"
  SWIFT_ARGS=()
  NAME="NeverQuestAlone Capture"
  USAGE="NeverQuestAlone Capture reads the small strip of colored squares that the NeverQuestAlone addon draws in the top-left corner of the World of Warcraft window. It captures only that corner of that window and keeps no images."
  COPYRIGHT="MIT. Part of NeverQuestAlone (fork of wow-ai)."
fi
# Both slices in one run, in a build folder of their own (this Mac's slice alone keeps its own).
if [ "$UNIVERSAL" -eq 1 ]; then
  if [ "$PUBLIC" -eq 1 ]; then
    SWIFT_ARGS=(--scratch-path "$HERE/.build-public-universal" -Xswiftc -DNQA_PUBLIC_ID)
  else
    SWIFT_ARGS=(--scratch-path "$HERE/.build-universal")
  fi
  SWIFT_ARGS+=(--arch arm64 --arch x86_64)
fi
APP="$OUT/NeverQuestAlone Capture.app"

VERSION="$(node -p "require('$HERE/../../../package.json').version" 2>/dev/null || echo 0.0.0)"

# An ad hoc build signs with no identity, so it never asks the keychain.
if [ "$ADHOC" -ne 1 ] && ! security find-identity -p codesigning 2>/dev/null | grep -q "\"$IDENTITY\""; then
  echo "Signing identity \"$IDENTITY\" not found in your keychain." >&2
  echo "Make it once: a code-signing certificate with exactly that name in your login keychain. A self-signed one" >&2
  echo "is enough (Keychain Access's Certificate Assistant makes one; NeverQuestAlone's own checkout has" >&2
  echo "tools/signing/create-identity.sh). Or pass --adhoc for a throwaway build that must never be granted" >&2
  echo "Screen Recording." >&2
  exit 2
fi

GEN="$HERE/Sources/NQACapture/BundleID.swift"
{
  echo "// Generated by build-app.sh from bridge/capture/mac/BUNDLE_ID (your build) and"
  echo "// app/desktop/build/bridge/capture/mac/BUNDLE_ID (NeverQuestAlone's, --public), the"
  echo "// one place each build's bundle id is set (PRD PF-6): Info.plist, the code requirement"
  echo "// in bridge/transport/capture.mjs and this check all read it. Edit those, not this."
  echo "#if NQA_PUBLIC_ID"
  echo "let captureBundleId = \"$PUBLIC_ID\""
  echo "#else"
  echo "let captureBundleId = \"$PRIVATE_ID\""
  echo "#endif"
} > "$GEN.tmp"
if cmp -s "$GEN.tmp" "$GEN"; then rm "$GEN.tmp"; else mv "$GEN.tmp" "$GEN"; fi

swift build -c release --package-path "$HERE" ${SWIFT_ARGS[@]+"${SWIFT_ARGS[@]}"}
BIN="$(swift build -c release --package-path "$HERE" ${SWIFT_ARGS[@]+"${SWIFT_ARGS[@]}"} --show-bin-path)/NQACapture"
if [ "$UNIVERSAL" -eq 1 ]; then
  for a in arm64 x86_64; do
    if ! lipo "$BIN" -verify_arch "$a"; then
      echo "the universal build has no $a slice: $(lipo -archs "$BIN")" >&2
      exit 1
    fi
  done
fi

STAGE="$OUT/.stage/NeverQuestAlone Capture.app"
rm -rf "$OUT/.stage"
mkdir -p "$STAGE/Contents/MacOS"
cp "$BIN" "$STAGE/Contents/MacOS/NQACapture"
# The linker's debug map names every object and source file by its absolute path on
# this machine; the packed copy ships without it (audit LS-06). swift build's own output
# keeps it for local debugging. codesign below signs the stripped file.
strip -S -x "$STAGE/Contents/MacOS/NQACapture"
sed -e "s/__VERSION__/$VERSION/g" -e "s/__BUNDLE_ID__/$BUNDLE_ID/g" -e "s/__NAME__/$NAME/g" -e "s/__USAGE__/$USAGE/g" -e "s/__COPYRIGHT__/$COPYRIGHT/g" "$HERE/Info.plist" > "$STAGE/Contents/Info.plist"
printf 'APPL????' > "$STAGE/Contents/PkgInfo"

if [ "$ADHOC" -eq 1 ]; then
  codesign --force --sign - --identifier "$BUNDLE_ID" "$STAGE"
else
  codesign --force --sign "$IDENTITY" --identifier "$BUNDLE_ID" --timestamp=none "$STAGE"
fi
codesign --verify --strict "$STAGE"

mkdir -p "$OUT"
rm -rf "$APP"
mv "$STAGE" "$APP"
rm -rf "$OUT/.stage"
echo "built: $APP (bundle id $BUNDLE_ID; $(lipo -archs "$APP/Contents/MacOS/NQACapture"))"
codesign -d -r- "$APP" 2>&1 | sed -n 's/^designated => /designated requirement: /p'
